polybar/polybar

cmake/build/options.cmake
examples/config
examples/config.bspwm
include/config.hpp.cmake
include/modules/temperature.hpp
src/components/controller.cpp
src/modules/temperature.cpp

Adds temperature module. A specific thermal zone `thermal-zone` can be set, and a threshold temperature `temperature-warn` can be specified for displaying a separate 'warning' label `label-warn`.

feat(temperature): Added temp module and examples

---

.gitignore
include/modules/bspwm.hpp
src/modules/bspwm.cpp

Added scrolling to the bspwm module. I also added `.swp` files to `.gitignore`.

feat(bspwm): added scrolling

---

include/modules/bspwm.hpp
src/modules/bspwm.cpp

I tried implementing those additional dimmed states as in #165. See if this makes sense to you. It works here but I might be missing something.

feat(bspwm): Additional dimmed states configuration

---

include/modules/mpd.hpp
src/modules/mpd.cpp

Introduces `<toggle-stop>` (`<toggle>` but stops instead of pauses).

Added stop toggle

---

include/adapters/mpd.hpp
src/adapters/mpd.cpp
src/modules/mpd.cpp

A trivial addition to the mpd module. :)

feat(mpd): Add support for date

---

include/modules/battery.hpp
src/modules/battery.cpp

I pretty much just reused existing mechanisms to add the ability to show battery drain/charge in watts. The new token is %consumption%

Add battery usage/charge in watts token %consumption%

---

src/modules/i3.cpp

Fix for #503 
Any critique is very much welcome!

fix(i3): Check whether current ws is focused before issuing scroll commands

---

README.md

As per discussion in https://github.com/jaagr/polybar/commit/802e69abafa575e3e38d36cca0c1ce07028dfb2e

Add more information on packages

---

src/modules/xkeyboard.cpp

Just to be consistent with the num lock part
This was driving me nuts when answering #654

Reuse caps_str

---

include/components/config.hpp
src/CMakeLists.txt
src/utils/file.cpp

Fixes (part of) #603 and #719.

fix(config): Expand all environment variables and file references

---

src/components/bar.cpp
src/components/renderer.cpp

This fixes #760
Now the proposed solution to #758 should work properly

fix(renderer): Properly support nested actions

---

include/modules/github.hpp
src/modules/github.cpp

This PR aims to fix the #810 and also contains small refactor for the github module.

Githubmodule noconnection

---

README.md
contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD
include/version.hpp

This is a first draft for the polybar 3.1.0 release.
**Things to do before merging:**
**Things to do after this is merged:**
Please tell me, if you think there are other things that need to be done for this release.
Closes #856

Release 3.1.0

---

doc/config.cmake
include/modules/bspwm.hpp
src/modules/bspwm.cpp

Same as the i3 workspace separator

feat(bspwm): Add workspace separator

---

include/modules/meta/factory.hpp

fix(alsa): use correct module_name

---

include/modules/mpd.hpp

Respect MPD_HOST env variable

---

include/modules/memory.hpp
src/modules/memory.cpp

feat(memory): Add memory used/free ramp

---

include/adapters/net.hpp
include/modules/network.hpp
src/adapters/net.cpp
src/modules/network.cpp

feat(net): Add unknown-as-up option

---

cmake/01-core.cmake

@patrick96 
This is building fine in here.
Thank you for your patience.

Ensures that libraries from dependencies in LOCALBASE are used.

---

src/components/bar.cpp

fix(cursor): add lock to motion handler

---

src/adapters/mpd.cpp
src/modules/mpd.cpp

While debugging #1055, I added some trace logging to the mpd module that I
think could be useful. They will also not spam the output too much, as they
are only executed on user clicks

mpd logging

---

doc/config.cmake
include/modules/battery.hpp
src/modules/battery.cpp

Would you be willing to merge this if I implement it?

Add animation-discharging (analog to animation-charging)

---

include/components/bar.hpp
src/components/bar.cpp
src/components/controller.cpp
src/main.cpp
tests/CMakeLists.txt
tests/unit_tests/components/bar.cpp

Since it looks like #701 will not be worked on anymore, I have taken the commit, added my tests, fixed the strtod issue and uploaded it to my repo.
I have already reviewed the PR this is based on and have made no real changes to the code, so I am going to merge this immediately.

Added support for mixed percent/pixel values for bar geometry

---

build.sh

Make question enable the user to use GCC as the compiler even if clang
is installed on the machine.

Add a question regarding compiler to `build.sh`.

---

src/drawtypes/ramp.cpp

Fixes https://github.com/jaagr/polybar/issues/1328

Ramp: evenly map to states

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD
include/version.hpp
src/components/controller.cpp
src/drawtypes/ramp.cpp
src/modules/i3.cpp

I want to try to release a patch release with the new process as soon as possible to work out any kinks.
This adds #1340, ~#1341~, and #1312 to version 3.2

Release 3.2.1

---

.ycm_extra_conf.py
tests/CMakeLists.txt
tests/unit_tests/utils/string.cpp

These are a few commits made in #1237 that are not directly related to the config parser. I'd like to merge these before I start with the other PRs

config_parser: Preparations

---

include/modules/alsa.hpp
include/modules/pulseaudio.hpp
src/modules/alsa.cpp
src/modules/pulseaudio.cpp

Use `interval = N`, fixes #1361.

feat(volume): adjustable volume intervals

---

src/components/logger.cpp

The current colors are barely legible

refactor(logger): Use better contrast for trace

---

src/x11/tray_manager.cpp

See #591. This is the patch jaagr worked on. Some people report this is working, or at least making things better.

fix(tray): Reconfigure tray on error

---

README.md

Including configs for the examples images shown here on README.md
closes #1403

Adding link to some polybar configuration examples

---

include/modules/memory.hpp
src/modules/memory.cpp

bar-used currently only supports internal memory, added support to have a bar for swap

Added swap memory support for bar-used

---

contrib/polybar.aur/PKGBUILD
include/modules/cpu.hpp
include/version.hpp
src/modules/cpu.cpp

Revert "Add ramp-padding capabilities to module/cpu"

---

include/cairo/context.hpp
include/cairo/font.hpp
include/cairo/surface.hpp
include/cairo/utils.hpp
include/components/config.hpp
include/components/controller.hpp
include/drawtypes/label.hpp
include/events/signal_emitter.hpp
include/modules/date.hpp
include/modules/i3.hpp
include/utils/command.hpp
include/utils/scope.hpp
include/utils/socket.hpp
include/utils/throttle.hpp
include/x11/winspec.hpp
src/cairo/utils.cpp
src/components/bar.cpp
src/components/builder.cpp
src/utils/bspwm.cpp
src/utils/command.cpp
src/utils/inotify.cpp
src/utils/process.cpp
src/utils/socket.cpp
src/x11/tray_manager.cpp

doc: Convert @ to \ doxygen commands

---

README.md

Just added some center alignment to the top elements of the README.md.

Added alignment to README.md

---

src/modules/script.cpp

This adds support for double-click handlers in the custom/script module
(for all buttons; left, right and middle).

Support double-clicks in custom/script.

---

include/adapters/net.hpp
src/adapters/net.cpp

Currently the polybar fails to detect bridge interface, Issue reference :- https://github.com/jaagr/polybar/issues/1522.
I have updated the code to add the support for bridge interface
EDIT: Fixes #1522

Added support for bridge interface

---

include/modules/cpu.hpp
src/modules/cpu.cpp

Adding option not to normalize cpu usage (#1516)
EDIT: Closes #1516

feat(cpu): Add normalize-load

---

README.md
contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD
include/version.hpp

3.3.0, finally!
I have already written the changelog in the [release draft](https://github.com/jaagr/polybar/releases)
**After Release Checklist**

Release 3.3.0

---

src/modules/xworkspaces.cpp

Extraction from #882 in order to resolve #1462 individually. If a more elegant way of writing this would be better, I am open to learning it.

(xworkspaces) handle div/0 when monitors changed a lot

---

contrib/polybar.aur/PKGBUILD

I made some last minute changes and forgot to update #1586

aur: fix tar url

---

src/modules/i3.cpp

Fix i3 crashing without label-state

---

include/components/bar.hpp
src/components/bar.cpp
tests/unit_tests/components/bar.cpp

Resolves #1567, also prevents negative sizes from being returned after format parsing.

Border percentages

---

include/x11/atoms.hpp
src/components/renderer.cpp
src/x11/atoms.cpp
src/x11/background_manager.cpp
src/x11/connection.cpp
src/x11/tray_manager.cpp

This fixes #1582 and #1585 and a few minor issues I found during debugging.

Fixes for background handling

---

include/x11/extensions/randr.hpp
src/components/bar.cpp
src/main.cpp
src/x11/extensions/randr.cpp

feat(monitor): use primary monitor as default

---

doc/config.cmake
include/modules/xbacklight.hpp

Fix: replace 'alot' with 'a lot'

---

include/components/types.hpp
src/components/bar.cpp

refactor(bar): Remove bar_settings.center

---

include/modules/xworkspaces.hpp
include/x11/ewmh.hpp
src/modules/xworkspaces.cpp
src/x11/ewmh.cpp

TEAMEDIT:
Fixes #1491 
Fixes #248
Closes #904

xworkspace support window manager with less names than desktops

---

src/modules/xkeyboard.cpp

Fix xkeyboard crashing when indicators where enabled

---

version.txt

We had quite some changes to the build system and also some new features so a new release is in order :smiley: 
This will likely be the last release that we do with the current branching model with dangling release branches. Afterwards we want to try and move over to something like git-flow as suggested by @Ovsyanka in #1780.
I have already created a [draft release](https://github.com/polybar/polybar/releases), please go over the changelog quickly and see if I made some obvious mistakes.
**After Release Checklist**

Release 3.4.0

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

I have already uploaded these to the AUR

Update PKGBUILDs for 3.4.0

---

.travis.yml

Combine the information into one line.

travis: create an irc one-liner

---

include/modules/xworkspaces.hpp
src/modules/xworkspaces.cpp

My plan is grand and all-encompassing: list all occupied workspaces.
So far, I list all workspaces not currently visible on another workspace. I would be very grateful for input on how to resolve this to a usable state... 
This is supposed to fix #874 
TEAMEDIT:
Fixes #1444 
Fixes #1033

feat(xworkspaces): List occupied workspaces

---

contrib/rpm/polybar.spec

Adjust version number.
Add new dependencies.
Explicitly ask for Python 3.

Update spec file

---

include/utils/string.hpp
src/modules/bspwm.cpp
src/modules/i3.cpp
src/modules/xkeyboard.cpp
src/modules/xworkspaces.cpp
src/utils/string.cpp
tests/unit_tests/utils/string.cpp

Resolves #1881.
I didn't use the new function everywhere most of the time we need to ignore empty tokens.

Add a tokenize function to take empty tokens into account

---

include/cairo/context.hpp
include/errors.hpp
include/utils/string.hpp
src/components/renderer.cpp
src/modules/bspwm.cpp
src/modules/i3.cpp
src/modules/ipc.cpp
src/modules/xkeyboard.cpp
src/modules/xworkspaces.cpp
src/utils/string.cpp
tests/unit_tests/utils/string.cpp
version.txt

I think the fix for the block alignment in the renderer deserves a new patch release. This release includes the commits from the PRs #1893, #1936, #1951, #1967, and polybar/xpp#20
The release draft is [here](https://github.com/polybar/polybar/releases/tag/untagged-a999127eaff24cfc5c0a).
EDIT: I have also pulled the fixes for gcc10

Release 3.4.2

---

doc/dev/packaging.rst
doc/index.rst

I have also created issue #1971 to inform package maintainers about changes to how polybar is built.

doc: Write page for package maintainers.

---

include/modules/backlight.hpp
include/utils/file.hpp
src/modules/backlight.cpp
src/utils/file.cpp

TEAM EDIT:
Adds the `enable-scroll` key in the backlight module.

backlight: enable changing via scroll

---

src/drawtypes/iconset.cpp
tests/CMakeLists.txt
tests/unit_tests/drawtypes/iconset.cpp

fix(iconset): Try exact match before fuzzy match

---

contrib/bash/polybar
contrib/zsh/_polybar
doc/man/polybar.1.rst
include/components/config.hpp
include/components/logger.hpp
include/modules/meta/base.inl
src/adapters/pulseaudio.cpp
src/components/config_parser.cpp
src/components/controller.cpp
src/components/logger.cpp
src/components/renderer.cpp
src/components/screen.cpp
src/main.cpp
src/modules/bspwm.cpp
src/x11/tray_manager.cpp

**Release Note:**
This requires an update on the font wiki page where it suggests using info logging. It also requires updating the home wiki page with the new usage.
**/Release Note:**
This adds a new default log level 'notice' for things the user should know about but that aren't warnings. Please read my commit messages for more details and motivations.

Log notice

---

README.md

Polybar is now finally available in Debian (and it's derivatives)! :heart: 
Closes: #1054
Also closes: #1959

Add installation instructions for polybar on Debian

---

include/utils/socket.hpp

Fix compilation under gcc10

---

contrib/polybar.aur/PKGBUILD

I already pushed the new PKGBUILD to the AUR

aur: Update PKGBUILD for 3.4.3

---

doc/conf.py

The tag is added to the 'deprecated', 'versionadded', and the
'versionchanged' directives.

doc: Add '(unreleased)' tag for unreleased versions

---

src/components/config_parser.cpp
tests/unit_tests/components/config_parser.cpp

Closes #2075
Add a check to handle the byte order mark.

fix(config_parser): Gracefully handle BOM

---

include/utils/math.hpp
src/adapters/alsa/mixer.cpp
tests/unit_tests/utils/math.cpp

Solves: https://github.com/polybar/polybar/issues/2173

feat(alsa): Remove upper bound to get_volume

---

doc/man/polybar.5.rst

This should reflect the changes from #2026

doc: Reflect config fallback in config

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/build.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
SUPPORT.md

Each new PR will include this template that I am currently using. 
This should make it easier to find the information we need for reviewing and also let contributors know what kind of information we want from them.
I also updated the issue templates to be more explicit about what information we want.
Finally, I added a `CONTRIBUTING.md` file that describes what one needs to consider when opening a new issue or PR and updated the README to reflect that.

doc: PR template and contributing guidelines

---

include/utils/string.hpp
src/modules/memory.cpp
src/utils/string.cpp
tests/unit_tests/utils/string.cpp

Display binary unit prefixes in memory module

---

doc/man/polybar.5.rst

Thanks to u/TheNextPoetician for reporting on reddit
https://www.reddit.com/r/Polybar/comments/k4llsx/typo_in_the_man_page/

fix(doc): Typo

---

.github/ISSUE_TEMPLATE/build.md

github: Typo in build issue template

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

New PKGBUILD for 3.5.0, has already been pushed to the AUR
#2253

aur: Update PKGBUILD for 3.5.0 release

---

src/modules/fs.cpp

This pull request fixes the bug in #2283. Somehow my dumbass decided to move the code that replaces fs tokens from build() to update() and cause info of the last mount point to be used to display all mount points.
Moved the code back to build() and fixed the problem.
Fixes #2283

Fix #2283: Display wrong partition information

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

aur: Update PKGBUILD for 3.5.1 release

---

tests/CMakeLists.txt.in

tests: Update gtest to newest commit

---

include/modules/meta/base.hpp
include/modules/meta/base.inl
version.txt

This only contains changes from #2296 because we broke legacy actions in #2270
Post-release checklist:
Draft Release: https://github.com/polybar/polybar/releases/tag/untagged-a6e024ef57c6aec0ccdb

Release 3.5.2

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

aur: Update PKGBUILD for 3.5.2 release

---

.codecov.yml

It seems that tests/* and lib/* don't actually exclude all the files in
codecov

codecov: Recursively ignore test and lib folder

---

.codecov.yml

codecov: Disable pull request annotations
Codecov would add code comments (annotations) to PR diffs whenever a
line was not covered by tests. This isn't really useful to us right now
and just produces noise.

codecov: Disable pull request annotations

---

CONTRIBUTING.md

I forgot to add the changelog section to the table of contents in `CONTRIBUTING.md`

doc: Add changelog to CONTRIBUTING.md TOC

---

doc/conf.py

If git is not available (and it doesn't have to be when building from a
source archive) building the documentation fails because we use
`git rev-parse` to determine whether a certain version is unreleased.
We now use the version.txt file to do this check
This uses the packaging library, but this should not introduce a new
dependency because sphinx depends on setuptools which also depends on
that library.
Fixes #2309

doc: Don't use git for checking version number

---

README.md

Adds a badge showing the total number of downloads to the README

readme: Add downloads badge

---

CONTRIBUTING.md
README.md

This should be merged after https://github.com/polybar/polybar.github.io/pull/18 because it links to the blog post in this PR which is not yet released.

Add links to polybar collective

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.5.3

---

README.md

I updated from where official polybar packages are available and added an entry for ubuntu 20.10

Cleanup Getting Started Section

---

CHANGELOG.md
src/components/controller.cpp
version.txt

New year, new release. This is just a small bugfix release for configs that use things like `}%{` or `}` (only at the end of a label) outside of formatting tags
Post-release checklist:
Includes the fix for #2331

Release 3.5.4

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.5.4

---

src/modules/xworkspaces.cpp

fix(xworkspaces): Handle -1 value for _NET_WM_DESKTOP

---

.github/workflows/ci.yml

CI: apt update before installing doc dependencies

---

src/modules/alsa.cpp

In #2336, I forgot to call the action prologue in the alsa module.

alsa: Call action_epilogue

---

CHANGELOG.md
doc/conf.py

The VersionChange class is not available in older versions of sphinx, so we just disable it
Fixes #2356

fix(build): Only change VersionDirective if supported

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.5.5

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Since we parse version strings in `doc/conf.py`, we now depend on `python-packaging`. 
I also added the dependency to the compiling page

PKGBUILD: Add python-packaging as build dependency

---

contrib/polybar.aur/PKGBUILD

Fixes #2416
Ref: https://github.com/polybar/i3ipcpp/pull/11

Fix abort in i3 module with new ArchLinux flags

---

CHANGELOG.md

This brings #2417 into the hotfix release
Ref #2417

Fix i3 module assertion failure

---

CHANGELOG.md
doc/conf.py
src/x11/tray_client.cpp
src/x11/tray_manager.cpp
version.txt

Release 3.5.6

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

We can now remove the temporary fix for the i3 crash

Update PKGBUILD for 3.5.6

---

README.md
SUPPORT.md
doc/index.rst

Change over all IRC mentions to libera

---

tests/CMakeLists.txt.in

gtest recommends using the `master` branch as it follows the "Live at
Head" philosophy.
[1]: https://github.com/google/googletest#live-at-head

Use master branch for googletest

---

doc/man/polybar.1.rst

It should be clear that `polybar -M` represents all valid monitor names.

doc: Update description of polybar -m/-M

---

include/adapters/net.hpp
src/adapters/net.cpp
src/modules/network.cpp

Regression from unreleased feature, doesn't require changelog entry.
Caused by #2025
Fixes #2496

fix(net): Check if interface is valid first.

---

README.md

Updates README.md now that polybar is on Debian stable.
Similar CR for the github pages website:
https://github.com/polybar/polybar.github.io/pull/25

Update Debian installation instructions

---

CHANGELOG.md
include/x11/tray_client.hpp
include/x11/tray_manager.hpp
include/x11/xembed.hpp
src/x11/tray_client.cpp
src/x11/tray_manager.cpp
src/x11/xembed.cpp

The icon not supporting XEMBED is not fatal, we just treat is as always
mapped.
Fixes #2479
Fixes #2442

tray: Properly handle missing _XEMBED_INFO

---

CHANGELOG.md
src/modules/ipc.cpp

fix(ipc): Replace all %pid% tokens

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.5.7

---

CHANGELOG.md
include/components/config.hpp
include/modules/script.hpp
include/utils/command.hpp
include/utils/process.hpp
src/modules/script.cpp
src/utils/command.cpp
src/utils/process.cpp
tests/unit_tests/utils/process.cpp

This PR wil add the `env-*` config option in the script module
Fixes  #2090.
Document the `env-*` option for the 'script' module in the wiki.

feat(script): Environment field in custom/script

---

CHANGELOG.md
cmake/cxx.cmake
include/adapters/script_runner.hpp
include/components/eventloop.hpp
include/modules/meta/base.inl
include/modules/script.hpp
include/utils/command.hpp
include/utils/file.hpp
include/utils/io.hpp
src/CMakeLists.txt
src/adapters/script_runner.cpp
src/modules/script.cpp
src/utils/command.cpp
src/utils/file.cpp
src/utils/io.cpp
tests/unit_tests/utils/command.cpp

* Feature
* Optimization
* Documentation Update
* Other: *Replace this with a description of the type of this PR*
TODO
Fixes #1978 
* This PR requires changes to the Wiki documentation (describe the changes)
* This PR requires changes to the documentation inside the git repo (please add them to the PR).

script: Fix concurrency issues

---

src/main.cpp

Fix message for deprecated config name

---

CHANGELOG.md
include/adapters/net.hpp
src/adapters/net.cpp
src/modules/network.cpp

This PR adds the %mac% option to the internal network interface modul
Closes #2568

Add mac address option

---

CHANGELOG.md
src/modules/alsa.cpp

The `alsa` module now supports middle and right button events (just like the `pulseaudio` module).
Closes #2566

feat(alsa): add middle and right mouse button events

---

include/components/bar.hpp
include/utils/math.hpp
src/modules/battery.cpp
tests/unit_tests/utils/math.cpp

I beleive it is a good thing to have less code. So I removed `min` and `max` with same functions from stl.

removed min and max from math_util and replaced them with std::min and

---

src/polybar-msg.cpp

If a single connection fails, other connections are kept intact.

polybar-msg: Better error messages

---

src/modules/battery.cpp

Otherwise we have to replicate the fallback logic for LOW -> DISCHARGING
in multiple places.
I have not tested this yet on a laptop, but I'm pretty sure this will fix the issue.
EDIT: Testing this on my laptop, everything seems to work and the bug is indeed fixed.
Fixes #2379
Closes #2392

fix(battery): Replace tokens for all labels

---

src/modules/bspwm.cpp
src/modules/i3.cpp
src/modules/xworkspaces.cpp

Emit error when workspace mapping has invalid format

---

CHANGELOG.md
doc/dev/release-workflow.rst
version.txt

See `CHANGELOG.md`
This is planned to be released on Tuesday March 1st.
The draft release can be found [here](https://github.com/polybar/polybar/releases/tag/untagged-5b6f95b8e1084e2ca6c7) (members only).
I have already written the release blog post: https://github.com/polybar/polybar.github.io/pull/32
**Post-release checklist:**
The wiki is updated with all changes (as described in all the PRs for this release)

Release 3.6.0

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.6.0

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Fix PKGBUILDs

---

README.md
cmake/01-core.cmake
cmake/05-summary.cmake
doc/man/polybar.1.rst

Documentation update for 3.6

---

CHANGELOG.md
include/cairo/context.hpp
include/ipc/msg.hpp
include/modules/date.hpp
include/modules/fs.hpp
include/modules/github.hpp
src/adapters/net_nl.cpp
src/modules/fs.cpp

Fixes #2614
Ref: https://gcc.gnu.org/gcc-12/porting_to.html

build: Add missing includes

---

include/tags/context.hpp
include/tags/dispatch.hpp
src/components/renderer.cpp
src/tags/dispatch.cpp
tests/unit_tests/tags/dispatch.cpp

tests: Use fakes in dispatch test

---

doc/user/ipc.rst

doc: Mention XDG_RUNTIME_DIR for IPC

---

CHANGELOG.md
README.md
cmake/01-core.cmake
cmake/05-summary.cmake
cmake/cxx.cmake
doc/CMakeLists.txt
doc/man/polybar.1.rst
doc/user/ipc.rst
include/cairo/context.hpp
include/ipc/msg.hpp
include/modules/date.hpp
include/modules/fs.hpp
include/modules/github.hpp
include/utils/units.hpp
include/x11/tray_manager.hpp
src/adapters/net_nl.cpp
src/adapters/script_runner.cpp
src/components/bar.cpp
src/modules/fs.cpp
src/polybar-msg.cpp
src/utils/units.cpp
tests/unit_tests/utils/units.cpp
version.txt

**Post Release Checklist:**
Contains fixes from the following PRs:
* #2613 
* #2616 
* #2612 
* #2619
* #2620 
* #2621 
* #2624

Release 3.6.1

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.6.1

---

README.md

Add manjaro in https://github.com/polybar/polybar#installation

add manjaro

---

CHANGELOG.md
include/components/types.hpp
include/x11/window.hpp
src/components/bar.cpp
src/x11/window.cpp

fix: Support negative struts

---

src/components/controller.cpp
src/modules/xworkspaces.cpp

fix(xworkspaces): Crash if number of desktops too small

---

CHANGELOG.md

It was mistakenly added to the 3.6 changelog

Fix changelog entry for interval-fail

---

CONTRIBUTING.md
doc/conf.py
doc/dev/getting-started.rst
doc/dev/style-guide.rst
doc/dev/testing.rst
doc/index.rst

Move developer documentation to repo

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.6.2

---

CHANGELOG.md
src/modules/battery.cpp

fix(battery): polling-interval not working

---

doc/user/actions.rst

The label-open was missing, making the snippet not work as-is.
In addition, backgrounding programs is no longer necessary
Ref #2686

doc: Fix menu module action migration example

---

CHANGELOG.md
src/modules/xworkspaces.cpp

fix(xworkspaces): Update on _NET_DESKTOP_VIEWPORT

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

This way changes to the default config made by users are preserved if
polybar ever changes the default config
Ref: https://aur.archlinux.org/packages/polybar-git#comment-863283

Add backup directive to PKGBUILD

---

CHANGELOG.md
doc/user/actions.rst
include/adapters/pulseaudio.hpp
include/components/renderer.hpp
include/ipc/ipc.hpp
src/adapters/pulseaudio.cpp
src/adapters/script_runner.cpp
src/components/bar.cpp
src/components/controller.cpp
src/components/renderer.cpp
src/ipc/util.cpp
src/modules/battery.cpp
src/modules/xworkspaces.cpp
src/x11/window.cpp
version.txt

Release 3.6.3

---

contrib/polybar-git.aur/PKGBUILD
contrib/polybar.aur/PKGBUILD

Update PKGBUILD for 3.6.3

---

README.md

Current version backports is bullseye.

Updated instructions for installing on Debian

---

include/events/signal.hpp
include/events/signal_fwd.hpp
include/x11/tray_manager.hpp
src/components/renderer.cpp
src/x11/tray_manager.cpp

implements hiding of the tray as discussed in  #2689
Closes part of  #2689

tray: implement hiding functionality

---

README.md

change the openSUSE description in README.md, obselete version.

change openSUSE description

---

src/x11/tray_manager.cpp

fix: tray flickers due to excessive redrawing/visibility changing

---

include/components/config_parser.hpp
src/components/config_parser.cpp
src/main.cpp
tests/unit_tests/components/config_parser.cpp

Doesn't need to be a class field

config_parser: Pass barname as argument to parse()

---

include/x11/atoms.hpp
src/modules/xwindow.cpp
src/x11/atoms.cpp

xwindow: Also listen for WM_NAME changes

---

CHANGELOG.md
include/components/types.hpp
src/components/bar.cpp

Setting option `enable-struts` to false will prevent polybar from configuring struts.
Closes #2769

option to turn off struts

---

.clang-format
CHANGELOG.md
cmake/cxx.cmake
src/utils/string.cpp

Now requires gcc8 or clang7
Update to mention new required compiler versions (gcc8 or clang7) and package names

build: Bump C++ to C++17

---

CHANGELOG.md

Pulls in fix in i3ipcpp repo: https://github.com/polybar/i3ipcpp/pull/12
Fixes https://github.com/polybar/polybar/issues/2888
Ref https://github.com/i3/i3/discussions/5352

fix(i3): Deal with negative coordinates

---

.github/workflows/ci.yml
.github/workflows/release.yml
src/x11/xresources.cpp

The coverage job fails because of the outdated codecov action and the checkout v2 action uses a deprecated version of nodejs

ci: Update codecov and checkout actions

---

src/x11/tray_manager.cpp

The tray should be vertically centered in the inner area of the bar. Unequal top and bottom borders should not affect the alignment relative to other text.
Fixes #2950

fix(tray): Vertically center in inner bar area

---

src/modules/i3.cpp

Prints the output and exit code of 'i3 --get-socketpath' if it fails and prints the socket path if the connection fails.
Ref polybar/i3ipcpp#13
Ref #2942
Also includes the i3 formatting update polybar/i3ipcpp#14

i3: Better error reporting when connection fails

---

include/components/config.hpp
src/components/config.cpp

Refactor `config::dereference*`  functions to return `string` and call `convert<T>` accordingly

Refactor config::dereference*

---

include/modules/meta/base.hpp
src/modules/meta/base.cpp

Remove unused field module_format::tags

Cleanup module_format::tags

---

CHANGELOG.md
doc/config.ini
src/x11/legacy_tray_manager.cpp

Part of #2689
All the tray settings in the wiki need to be marked as deprecated and mention the new tray module.

Deprecate legacy tray options

---

README.md

I noticed that our README pointed to an outdated link for the polybar FreeBSD port.
@Tectu are the installation instructions otherwise still accurate?

doc: Fix FreeBSD link

---

.readthedocs.yaml
doc/requirements.txt

Since August 7, 2023, readthedocs will not install the rtd theme by default anymore.
Ref: https://blog.readthedocs.com/python-core-requirements-changed/

doc: Explicitly specify sphinx rtd theme dependency

---

doc/conf.py
doc/requirements.txt

Provides real-time search on readthedocs
Ref: https://readthedocs-sphinx-search.readthedocs.io

feat(doc): Add rtd search extension

---

CHANGELOG.md
contrib/polybar-git.aur/PKGBUILD

Update PKGBUILD for 3.7.0

---

CHANGELOG.md
include/common.hpp

build: Add missing headers in common.hpp

---

README.md

The release workflow never runs on the master branch (it runs on the release branch), so the badge would always show "no status"

doc: Fix "Release Workflow" badge

---

CHANGELOG.md
include/common.hpp
include/events/signal.hpp
include/events/signal_fwd.hpp
include/modules/meta/base.hpp
include/modules/tray.hpp
include/x11/legacy_tray_manager.hpp
include/x11/tray_manager.hpp
src/components/renderer.cpp
src/modules/meta/base.cpp
src/modules/tray.cpp
src/x11/legacy_tray_manager.cpp
src/x11/tray_manager.cpp
version.txt

TODOs
Includes:
* #3037
* #3038
* #3045
* #3052

Version 3.7.1

---

CHANGELOG.md

fix(doc): Wrong header level in changelog

---

contrib/polybar-git.aur/PKGBUILD

Update PKGBUILD for 3.7.1

---

CHANGELOG.md
src/x11/tray_manager.cpp

The vector::erase call needs to be supplied with the end of the range, otherwise only a single element is removed.
Fixes #3111

fix(tray): Clients not being removed properly

---

doc/config.ini
doc/user/modules/tray.rst

Unaware users may be confused by why the tray module is not shown in the default config and if they add it, they may be confused why only one of their bars shows the module.
Replaces #3134

doc: Improve tray documentation

---

CHANGELOG.md
src/modules/ipc.cpp

Before, it just showed '%output%'
Fixes #3131

fix(ipc): Clear output until initial hook finishes

---

.github/workflows/ci.yml

Codecov upload is currently broken
Backported to the hotfix branch in #3142

tests: Update codecov uploader action

---

.github/workflows/ci.yml

fix(ci): Get Codecov to work again

---

.github/workflows/ci.yml
.github/workflows/release.yml

ci: Update github actions

---

.clang-tidy
.github/workflows/ci.yml
.github/workflows/release.yml
CHANGELOG.md
doc/config.ini
doc/requirements.txt
doc/user/modules/tray.rst
include/modules/backlight.hpp
include/modules/meta/base.inl
include/utils/command.hpp
src/adapters/script_runner.cpp
src/components/renderer.cpp
src/drawtypes/label.cpp
src/modules/ipc.cpp
src/utils/command.cpp
src/x11/background_manager.cpp
src/x11/tray_manager.cpp
version.txt

Includes:
* #3081
* #3090
* #3091
* #3096
* #3112 
* #3119
* #3135
* #3140
* #3142
* #3145

Version 3.7.2

---

contrib/polybar-git.aur/PKGBUILD

Already pushed to the [AUR](https://aur.archlinux.org/packages/polybar-git)

Update PKGBUILD for 3.7.2

---

CHANGELOG.md
include/ipc/decoder.hpp
include/ipc/encoder.hpp
include/ipc/msg.hpp
include/utils/color.hpp
include/utils/string.hpp
src/ipc/encoder.cpp
src/utils/color.cpp

fix(build): Add missing cstdint includes (#3159)

---

README.md

Change description for openSUSE, change version and repository.

Change desc for openSUSE

---

CHANGELOG.md

Git merged the entry into the wrong section when #3078 was merged

doc: Fix changelog entry

---

tests/unit_tests/utils/string.cpp

Added to the string_util tests corner cases for empty strings and numerics plus a more complete permutation of "foo" and "bar" for the upper and lower tests

test: Added to string_util tests corner cases for empty strings and numerics
