contrib/lemonbuddy-git.aur/.SRCINFO, contrib/lemonbuddy-git.aur/PKGBUILD
Only for the '-git' package since the other one would also require a
version bump
=> Remove python executable replacment in PKGBUILD

.travis.yml
Somehow ubuntu on the travis server does not have
/usr/lib/python2.7/dist-packages in the path and thus the xcbgen module
cannot be found. Adding it to the PYTHONPATH fixes this
=> Fix broken travis build

include/modules/i3.hpp
Hello,
I like to be able to scroll through my workspaces, so I added scroll up and down events which send the command `workspace next` or `workspace prev`.
I also added the option `strip-wsnumbers` which is a feature of i3bar. If set to true the workspace label is split by `:` and only the second part is shown. This makes it possible to use numbered workspaces but only show the name.
=> feat(i3): Scrollable workspaces and strip-wsnumber option

include/adapters/alsa.hpp, include/modules/volume.hpp, src/adapters/alsa.cpp, src/modules/volume.cpp
I'm used to the volume mapping used by `amixer -M` and `alsamixer`, so I thought it would be useful to have an option which displays the volume this way instead of the raw percentage.
=> feat(volume): Added volume mapping

include/drawtypes/label.hpp, include/utils/string.hpp, src/drawtypes/label.cpp, src/utils/string.cpp
Added `string_util::format_minwidth` which allows for padding, expanding upon the `udspeed-minwidth` setting. The values which are most susceptible to shifting (volume, battery, cpu percentage, etc.) now use this function, but it might be beneficial to add it to all numerical values.
=> feat: add padding for values

include/drawtypes/label.hpp, src/components/builder.cpp, src/drawtypes/label.cpp
Since the `prefix` and `suffix` strings don't have spaces before/after, having separate left/right padding and margins is the only way to insert a space between them and the rest of the output.
=> feat: Add left and right padding and margins

src/modules/script.cpp
Shouldn't the default tag be `<label>` instead of `<output>`? Otherwise, it would just complain that it's deprecated even though the user hasn't set anything.
=> fix(script): set default tag to label

include/modules/bspwm.hpp, src/modules/bspwm.cpp
With this addition, adding
label-pseudotiled = P
will display P whenever a bspwm node is set to pseudo-tiled (the default keybind is Super+Shift+T).
Should be a trivial addition, but I compiled & tested on my computer nevertheless.
If approved, I'll edit the wiki to include the option.
=> feat(bspwm): Add support for pseudo tiled nodes

include/adapters/alsa/mixer.hpp, src/adapters/alsa/mixer.cpp, src/modules/volume.cpp
Because the "Master mixer" of the default soundcard does not work, I implemented a way to set a soundcard for the master, speaker and headphone mixer.
To set the soundcard(s):
```
[...]
[module/volume]
master-soundcard = <soundcard's name>
speaker-soundcard = <soundcard's name>
headphone-soundcard = <soundcard's name>
[...]
```
I tested this by setting the ```master-soundcard``` to (in my case) ```hw:2```, which is - in my case - an external USB soundcard.
=> Improvement of alsa::mixer and the volume module

src/modules/xwindow.cpp
There is an issue when using the Xwindow module. By default, it will use the __NET_WM_VISIBLE_NAME property to set the title, unless it's empty. This property displays certain characters (like the apostrophe) as "\&apos;" in Firefox, or any other window which uses HTML or similar code. In i3, for example, using the "title_format" command:
`for_window [floating] title_format "<span font=FontName> %title </span>" `
will display the whole string in the bar, instead of the formatted title. 
The __NET_WM_NAME property, however, shows the title correctly.
=> Gives priority to __NET_WM_NAME 

include/drawtypes/iconset.hpp, include/modules/bspwm.hpp, include/modules/i3.hpp, src/drawtypes/iconset.cpp, src/modules/bspwm.cpp, src/modules/i3.cpp
Thanks for this project, I recently switched from i3bar and am loving it! :)
I was playing around with setting icons for different workspaces, and wanted a way to match the icon id as a substring of the workspace name, since my web browser is not always on the same numbered workspace.
I implemented this along with a configuration switch for both bspwm and i3: `fuzzy-match`. It is false by default, which uses the old matching algorithm.
Let me know if anything is not right, I'm still new to c++. Thanks!
=> feat(bspwm,i3): Fuzzy-matching names for icons

include/x11/xresources.hpp
Not sure what "String" was supposed to do, my tests with xcb-xrm gives that
res_class==NULL properly gets the resource value, =="String" does not.
=> res_class==NULL to properly get the resource

include/utils/inotify.hpp, src/components/controller.cpp, src/utils/inotify.cpp
This fixes a "bug" where polybar wouldn't reload on a configuration file change on some configurations of vim, which don't actually issue any `IN_MODIFY` events because they choose to move the file, replace it with a new one, and then delete the file instead.
To work around this, we now also listen for `IN_IGNORED` which fires when the file we are watching is destroyed. When this happens, we re-attach the configuration file watcher to the new file and reload.
=> Ensure reloading when IN_IGNORED fired on config

include/cairo/font.hpp, src/components/renderer.cpp
(See #363). This tries to mimic the old renderer's behavior as closely as possible. In the absence of any information, DPI is assumed to be 96x96. DPI can be configured on a per-bar basis using the configuration key "dpi".
To use the DPI configuration from Xresources (if built with support), one can specify the following in the bar config:
```
dpi = ${xrdb:Xft.dpi:96}
```
Individual keys `dpi-x` and `dpi-y` are supported. Negative values are taken to mean "automatic" where the DPI will be calculated from screen features (accuracy here will depend on your hardware, YMMV).
=> Use proper font scaling based on DPI

src/modules/memory.cpp
This PR fixes #405.
Since 3.4, `/proc/meminfo` contains a `MemAvailable` field, which polybar uses to determine
`(gb|mb)_free` and `(gb|mb)_used`. This commit adds a fallback for when `MemAvailable` does
not exist, allowing a fairly-accurate approximation on older kernels.
This commit also removes the reliance on the exact order fields appear in `/proc/meminfo`.
=> Implement memory updating for pre-3.4 kernels

include/utils/string.hpp, src/drawtypes/label.cpp, src/utils/string.cpp
This helps ensure that when a string is truncated it is not done in the middle of a utf8 multi-byte sequence.
This doesn't 100% correspond to user-perceived characters, but it should be pretty close in most cases.
I think this might fix issue #393.
=> fix(label): Truncate label replacements based on codepoint count

src/components/builder.cpp
This should fix the remaining problems in issue #393, since I missed a spot in the last PR.
=> fix(builder): Use unicode-aware truncation for label-maxlen

include/modules/xworkspaces.hpp, include/x11/atoms.hpp, include/x11/ewmh.hpp, include/x11/icccm.hpp, src/modules/xworkspaces.cpp, src/x11/atoms.cpp, src/x11/ewmh.cpp, src/x11/icccm.cpp
Listens for `WM_HINTS` changes in all windows and checks if the urgency bit is set, and sets the corresponding desktop state accordingly.
=> feat(xworkspaces): add urgent desktop detection

Makefile
Shells like dash do not support printing paths of more
than one argument with the builtin `command -vp`.
=> fix(build): POSIX compliant command usage

include/modules/bspwm.hpp, src/modules/bspwm.cpp
When focusing a desktop with the urgent flag, two events are received
from `bspc` simultaneously, separated by a newline character.
This was not handled correctly and the second event was discarded causing
the urgent style to be removed, but the focused style would remain on the
previously focused desktop.
This fixes the problem by handling any number of events that arrive at the
same time (separated by newlines).
=> fix(bspwm): Update when focusing urgent desktops

README.md
Polybar is now included in Nix/NixOS if y'all want to mention it in the README.
(as of https://github.com/NixOS/nixpkgs/pull/22222)
=> Mention NixOS with the other operating systems

cmake/templates/uninstall.cmake.in
As you can see [here](https://cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F), `install_manifest` file reference in this template is missing an extension.
=> install_manifest has a .txt extension

src/utils/string.cpp, tests/unit_tests/utils/string.cpp
Hi, I found that when the available fs free size was under 1Gb, it reported the right MB size but in GBs (like: 943 GB).
This should fix it
=> fs: Fix wrong size report

src/modules/mpd.cpp
Hello.
This should fix #500 
I also  added checks before `play()`, `pause()` and `stop()` for consistency, if you have any concerns please let me know.
=> fix(mpd): Check state before calling playback controls

include/modules/i3.hpp, src/modules/i3.cpp
Hey,
This fixes clicking on workspaces without an index.
=> fix(i3): Use ws name for click handling

include/modules/mpd.hpp, src/modules/mpd.cpp
@jaagr hey, 
This implements #524. 
Basically, in `module_formatter::add()` we check whether `fallback` is a format itself and try to get its value from the config if it is. That allows us to specify `format-online` as a fallback format for `format-playing`, `format-paused` and `format-stopped`.
I guess that the biggest downside to this approach is that we lose the ability to specify a default value in the case where no formats are found in the config. We could avoid that by turning  `fallback` into a vector, but I suppose that would affect all modules, so it might be a bit of an overkill. I'd like to hear your thoughts on this.
=> feat(mpd): Add state-specific formats

src/modules/xworkspaces.cpp
The ewmh module doesn't properly set the "active" workspace when using XMonad (and perhaps others) as referenced in #535 . Applying the code from #411 fixes that.
=> Fixes #535 and #411.

src/utils/http.cpp
Curl removed that header in https://github.com/curl/curl/commit/73a2fcea0b4adea6ba342cd7ed1149782c214ae3
http.cpp doesn't use anything from that header and compilation works for
fine with curl 7.54.1
Fixes #647
=> Remove curlbuild include

cmake/common/utils.cmake
If color output was surpressed, there was no way to tell in the cmake                                                              
summary, if a module is actually enabled or not.               
Now each module is prefixed with either a "[X]" to indicate it's enabled                                                           
or a "[ ]" to indicate it's not.
This is something that could have saved a lot of hassle in #644 
EDIT: It now looks like this:
=> Add textual indicator for module support

include/components/types.hpp
If the mouse was at the leftmost edge of the screen and there was an
action area from 0 to N, the click wouldn't register
Before if an action area was defined from A to B it was from A exclusive
to B inclusive now it is from A inclusive to B exclusive. This is the
same way that the pixel addresses work, since a pixel's coordinate is
defined by the top-left corner.
Fixes #661
=> Fix off by one error for action area

doc/config.cmake, include/modules/menu.hpp, src/modules/menu.cpp
expand-right defaults to true to preserve the current functionality
If set to false, the items in the menu will be added to the left of the
toggle label (instead of the right side)
Should resolve the issue discussed in #655 
`expand-right=true`:
`expand-right=false`:
=> feat(menu): Add expand-right option

src/modules/temperature.cpp
Adds support for all temperature data from libsensors. Users should set `hwmon-path` to the full desired sysfs path. Fixes #404.
Helpful tip: first find the desired sensor from `sensors` by looking at `/sys/class/hwmon/hwmon*/temp*_label` or `/sys/class/hwmon/hwmon*/name`, then run `readlink -f /sys/class/hwmon/hwmon*/temp*_input` to find the target of the symlink. Using `/sys/class/hwmon/...` in the config should be avoided because the device orders are not persistent (the order is based on whichever module loads first).
=> feat(temperature): Add hwmon sysfs support

cmake/01-core.cmake
There is no way to avoid this warning in the code itself, so we must suppress this warning if we wish to keep -Werror.
This is part of a series of pull requests that restore building of polybar on GCC. Once this is merged along with jaagr/xpp#6 and jaagr/i3ipcpp#2 (and the submodules updated after those merge), the project should build again with GCC 7.1.
=> fix(cmake): Suppress -Wnoexcept-type warning on GCC

src/components/renderer.cpp
The changes introduced in 389bae266976bdb35efcfc18d0bd0aa978fa5702 to
address #551 did not consider the left border
Now center modules are centered regardless of border (left or right)
settings or tray position
Fixes #672
=> fix(renderer): Correct center module position

contrib/polybar.aur/PKGBUILD
The `curl/curlbuild.h` header issue has been resolved after the last
release, as a consequence the AUR package doesn't build anymore without
altering the source before compiling.
This cherry-picks the fix commit to resolve the compile errors.
@jaagr Can you please update the PKGBUILD for the `polybar` package with the one in this PR
=> Fix curl compile errors in aur polybar package

include/modules/date.hpp, src/modules/date.cpp
Sensible upper limit of 1024 chars since anything of that length will
not be fully rendered on the bar anyways.
fixes #744
=> fix(date): date and time string limited to 63 chars

include/components/parser.hpp, src/components/parser.cpp, src/modules/meta/base.cpp
Fixes #639 and #544, as requested by @patrick96. Provides a non-breaking solution to the problem posed in #544.
Stacks are removed (including the font index `%{T}`), but now the tags of prefixes and suffixes are separated from the main output.
There might still be some optimizing to be done, as the reset flag `%{X-}` still sometimes appears when switching between two defined values: `%{B#8d7e45}prefix %{B- B#feffff}main`. Also, module-wide settings (`format-<type>`) are not applied to the prefix and suffix.
=> fix(modules): Separate prefix/suffix tags, revert tag stack

doc/config.cmake
It's quite obscure where to find that you can set a minimum width for tokens, and CPU usage will oscillate between 0-9 and 10+ quite frequently. I think that adding this to the example config will help users to find out that this feature exists, and avoid this annoying default.
=> Add minimum width to CPU percentage

src/adapters/alsa/mixer.cpp
I've built rpm packages for fedora and I run into an error on Fedora Rawhide.
`...use of undeclared identifier 'pow10'...`
Looking around this seems a quick fix with pow(10, ...).
It compiles now with these fixes.
=> Fixed a compilation error on Fedora Rawhide

src/modules/i3.cpp
Fixes dereference of `end()` iterator in case current workspace is not found (#824).
I'm not sure whether this should be logged or not, so I'd like to hear your opinion on that.
=> fix(i3): Check whether current ws is found

src/adapters/mpd.cpp
Fixes #815 by getting the mpd tag name or URI as fallbacks if the title is not found. The URI is parsed to find and return only the basename if found. This is similar to ncmpcpp's title, which should also follow this sequence of fallbacks.
=> feat(mpd): Get name and/or uri if title not found

src/components/renderer.cpp
Fixes #759 by only drawing text background when its color is different from the background color of the bar itself. Original check was made invalid by [this change](https://github.com/jaagr/polybar/commit/0bd8f1f69a8dfdb2f2800a6612c8acb7e6c86ed2#diff-543075e5874c51140b59304a24b67c78L208).
There is one small issue though: if the text background color is explicitly set equal to `background-0` it will be ignored.
=> fix(renderer): Only draw text bg if the color differs from the bar bg color

Makefile
Just a simple `help` target for the `Makefile` which list all of the targets with a single line `awk`.
So sometimes I could avoid opening the `Makefile` only to know the targets :smile:
=> feat(build): help target to list all targets

src/modules/mpd.cpp
Fixes the broken `format-online-*` options mentioned in #863 by retrieving them individually and applying them to the other formats if they exist.
=> fix(mpd): get format-online options for format-{playing,paused,stopped}

contrib/polybar-git.aur/PKGBUILD
version.sh is supposed to set the `GIT_TAG` macro in `version.hpp` to the
output of `git describe ...`, however it uses relative paths and can't
find `include/version.hpp`
`include/CMakeLists.txt` already has the same functionality so this is
not needed
=> fix(AUR): Remove failing call to version.sh

contrib/polybar.aur/PKGBUILD
Updates the polybar PKGBUILD to 3.1.0. Also adds `xcb-util-cursor` since this is a new release (I already pushed it to the AUR).
I think we should have a better way of updating the AUR package or the PKGBUILDs in this repo, so we only have to edit one of them and the other will be automatically updated. Should we have a bot or a script to do this for us?
=> fix(aur): update to 3.1.0

common/bump.sh
`common/bump.sh` still refers to .SRCINFO files and fails when run, so we should remove those references.
=> fix(bump.sh): remove references to .SRCINFO

include/adapters/mpd.hpp, include/modules/mpd.hpp, src/adapters/mpd.cpp, src/modules/mpd.cpp
This PR adds support for _icon-consume_ to the mpd module.
It works exactly like _icon-random_ and the alike.
=> feat(mpd): Add support for icon-consume

doc/config.cmake, include/modules/i3.hpp, src/modules/i3.cpp
Puts a label-separator node between workspaces on the bar. Since the
separator uses a label it can be configured like any other label
To-Do after merge:
=> feat(i3): Add workspace separator

include/adapters/mpd.hpp, src/adapters/mpd.cpp, src/modules/mpd.cpp
Only updating when an mpd event occurred would cause issues when mpd was
playing and the machine was put to sleep because the elapsed time was
calculated by taking the time difference of the last update and now which
would give you wrong numbers, if the machine was in standby in between.
Since the update function on the module is only called once a second (or
when an event happens), we can just update the data every time without a
huge performance hit.
Fixes #915
=> fix(mpd): Always update mpd data

include/modules/script.hpp, src/modules/script.cpp
This can be used to send signals to the script running (e.g. SIGUSR1, etc) which
makes it easier to have an updatable state inside the script. With this, it is
for example possible to have a two-state date script:
```dosini
[module/date]
type = custom/script
exec = /path/to/date.sh
tail = true
click-left = bash -c "kill -SIGUSR1 %pid%"
```
`date.sh`:
```bash
t=0
toggle() {
t=$(((t + 1) % 2))
}
trap "toggle" USR1
while true; do
if [ $t -eq 0 ]; then
date
else
date --rfc-3339=seconds
fi
sleep 1 &
wait
done
```
Todo:
=> feat(script): %pid% token for tail commands

README.md, build.sh, contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD, doc/config.cmake, include/modules/alsa.hpp, include/modules/meta/factory.hpp, include/modules/unsupported.hpp, src/components/controller.cpp, src/modules/alsa.cpp
Not exactly sure how we should deprecate a module name, because we don't have a function for that. If we used `log.warn()` we would have to pass `m_log` to `make_module()`. Right now it just throws an `application_error`.
=> volume: Change all volume module references to alsa

include/modules/meta/factory.hpp
Not sure why I changed the module name... it broke all module options because it tried to find `internal/alsa` when `internal/volume` was specified. Now the options should be properly detected.
=> fix(alsa): use correct name for deprecation

src/drawtypes/label.cpp
When using the same token multiple times in the same label with
different length properties, polybar would always use the settings for
the first token. This now replaces the tokens one by one, so that a new
token object is used for the length settings each time a token is used
again. Because the token objects are added in order, the replacement
always uses the right token object for the token that is replaced.
Fixes #971
=> fix(config): Use proper token object

src/modules/battery.cpp
Fixes the incorrect power unit conversion in the battery module. Credit to @MatthewLavine for the discovery and initial fix.
Fixes #928.
=> fix(battery): use power_now correctly

include/modules/mpd.hpp, src/modules/mpd.cpp
This bug was introduced in 645a3142a19747c252d24cc71414d40a8eb5f7dc
Fixes #979
=> fix(mpd): Check m_status before derefencing it

src/modules/battery.cpp
`path_battery` goes out of scope, so the stack reference becomes garbage
Fixes #985
=> Fix battery module crashing

README.md
Since we've recently [added](https://github.com/sourcemage/grimoire/commit/728bc1864077610f447ee960d55ac66ce9627fbe) polybar to our package base, it'd be good to have it the official support list.
=> Add Source Mage package for polybar

src/modules/xworkspaces.cpp
This is to fix `enable-scroll` setting being ignored for the xworkspaces module.
=> Respect 'enable-scroll' setting for xworkspaces module

README.md
There is no Debian release in GetDeb and according to [1] packages
from Ubuntu repositories can break a Debian system.
Fixes #1000
[1]: https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian
=> fix(doc): GetDeb packages not Debian compatible

src/modules/alsa.cpp
The old code causes a segmentation fault, if the speaker and headphone
soundcards differ.
=> fix(alsa): Use proper speaker mixer name and soundcard

src/adapters/mpd.cpp, src/modules/mpd.cpp
Before, polybar would crash, trying to throw a server error because
mpd_connection_get_server_error asserts that the error is of type server
error, but it isn't because it was cleared
=> fix(mpd): Clear mpd error after getting error info

src/components/config.cpp
There have now been several instances of people reporting that their
bars are not found and polybar not printing the config file name because
the error is thrown first, making it very difficult to debug
=> refactor(config): Print filename at very beginning

src/utils/http.cpp
When the internet connection is off, the github module stuck at the `curl_easy_perform` function.
Does not really recover from it, it is probably not a polybar/github module issue, but curl.
It can be "fixed" via disabling the shared connection.
=> fix(github): libcurl stuck at curl_easy_perform

doc/config.cmake, include/modules/temperature.hpp, src/modules/temperature.cpp
Adds two new tokens, `%temperature-c-n%` and`%temperature-f-n%`, to display the temperatures in those respectives scales without the appended unit.
This also deprecates the `%temperature%` token in favor of the scale specific tokens, `%temperature-c%` and `%temperature-f%`
=> feat(temp): Add temperature tokens without unit

cmake/02-opts.cmake, cmake/05-summary.cmake
Often we may need information from the user that is only available if
-l trace is used which requires most users to recompile polybar in debug
mode.
=> logger: Enable trace logging by default

src/components/bar.cpp
See this as a suggestion, i didn't want to create an issue for such a small fix.
> Changed loglevel for "No matching input area found" from warn to info
In my opinion it is irritating when polybar emits a warning when i click with a not defined button on an element. I didn't define that click handler, so everything should be fine
=> Changed loglevel to info

contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD
Polybar includes no header files from this library and doesn't use any
i3ipc_* functions
=> refactor(aur): Remove unused i3ipc-glib dependency

contrib/polybar.aur/PKGBUILD
Just got back from vacation and see that the new xcb-proto version breaks all
builds in the AUR. This is only a temporary fix until we do a proper release
containing the fix.
Will try to catch up on all the things I missed in the next few days
Fixes #1090
=> fix(aur): Use newest xpp commit to build with xcb-proto

README.md, contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD
The actual i3 package is also needed to build polybar with i3 support.
It is also listed as a makedepends, like that polybar will always work
with i3, even if the user only decides to install i3 later on.
=> aur: Add i3-wm dependency

cmake/01-core.cmake, cmake/03-libs.cmake, include/adapters/alsa/generic.hpp
Added support for FreeBSD. Uses libinotify wrapper for inotify calls. I also had to disable some compiler warnings as libinotify uses c99 extensions.
Fixes #239.
=> Added FreeBSD Support

src/modules/i3.cpp
This fixes issue #762 by reconnecting the socket if an error occurs.
=> fix(i3): Reconnect i3 IPC socket on restart/error (#762)

.exrc
This is oddly specific to jaagr's setup, and absolutely useless for everyone else.
=> fix: remove .exrc

include/modules/pulseaudio.hpp, src/modules/pulseaudio.cpp
volup, voldow, volmute, are caught by the alsa module, if there is an
alsa module on the bar.
=> fix(pulse): Use distinct event names

include/adapters/pulseaudio.hpp, src/adapters/pulseaudio.cpp
The new event case should now fall through if there was no sink specified in the config, so it gets the current default sink.
I also added a mutex for the queue because the callback is on a separate thread compared to the module which calls `process_events()`.
Fixes #1086.
=> fix(pulseaudio): get default sink on new events when using default, add mutex

include/settings.hpp.cmake
I didn't notice the guard withing setting.hpp.cmake when I submitted #1057
=> fix(log): Actually enable trace logging by default

include/modules/xwindow.hpp, src/modules/xwindow.cpp
If you use the current [config file](https://github.com/jaagr/polybar/wiki/Module:-xwindow) in the wiki entry for the xwindow module, not having an active window will still result in "Window: " being displayed in the bar. This doesn't really make sense IMO, so I added an if statement to clear the entire label (including the "Window: ") if there is no active window.
I could also add an option to make this configurable, but I don't really see why anyone would want the "Window: " to be displayed.
=> Clear entire xwindow label if no window is open

include/adapters/pulseaudio.hpp, src/adapters/pulseaudio.cpp
This reverts commit d430174f0b4c02d5dfc2eb818ed79410a2e19b4b.
Mutual exclusion is already guaranteed by the lock on
pa_threaded_mainloop
Fixes #1139
=> Revert "fix(pulseaudio): add mutex for queue"

include/adapters/pulseaudio.hpp, src/adapters/pulseaudio.cpp, src/modules/pulseaudio.cpp
Adds `max-volume` configuration.
If set to `true`  volume is capped at 150%, 
if `false`it's capped at 100%, 
unset = `true`
Fixes #1125
=> (pulseaudio) Add max volume configuration

src/modules/network.cpp
I don't see a reason why not to treat a negative result from `network::query` as a reason why the interface is down.
Is there something I'm missing here @NBonaparte?
Fixes #1163
=> fix(net): Mark not connected on querying failure

src/components/bar.cpp, src/components/builder.cpp, src/components/config.cpp, src/components/parser.cpp, src/components/renderer.cpp, src/ipc.cpp, src/modules/menu.cpp, src/modules/mpd.cpp, src/modules/temperature.cpp, src/x11/tray_manager.cpp
atoi, atof and so on have undefined behavior if anything goes wrong. We
now use strto*, but without error checking. In most places overflows and
the like *should* not happen. String to number conversions are only used
when reading data from other applications or from the config, if another
application gives unparsable strings or too large numbers, then most
likely there is something wrong with that application. If the error
comes from the user config, then the user has to live with values
provided by strto* on error (which are very reasonable)
Fixes #1201
=> fix: Stop using ato* for string to num conversion

include/adapters/pulseaudio.hpp, src/adapters/pulseaudio.cpp
Fixes #1167 by listening for changes in the default sink. Also, we can reduce the number of callbacks by using `@DEFAULT_SINK@` as the default sink name, so we don't have to retrieve the actual name.
While we're at it, I also fixed `max_volume` naming to be consistent.
=> fix(pulseaudio): listen for default sink changes, and use @DEFAULT_SINK@

src/adapters/net.cpp
As mentioned in #1215, gcc >=8 will complain, if strncpy truncates the
source string or gcc can prove there is no NUL terminating byte.
This also updates the i3ipcpp submodule where there was a similar error
Fixes #1215
=> fix(gcc): Fix -Wstringop-truncation warning

src/components/builder.cpp
The builder would convert bg and fg colors like #00000000 to #000 which
would make it loose its alpha channel.
Fixes #1183
=> fix(builder): Don't truncate colors with same channels

src/x11/tray_manager.cpp
I suspect that people that are seeing the tray above their fullscreen
windows get this exception
=> refactor(tray): Log restack failure as error

common/travis/install_xcb_xrm.sh
For some reason some of the travis builds fail with the following compiler errors:
```
/home/travis/build/jaagr/polybar/src/main.cpp:68:65: error: incomplete type 'polybar::v3_1_0::connection' named in nested name specifier
throw application_error("X connection error... (what: " + connection::error_str(xcb_error) + ")");
^~~~~~~~~~~~
/home/travis/build/jaagr/polybar/include/x11/types.hpp:30:7: note: forward declaration of 'polybar::v3_1_0::connection'
class connection;
^
/home/travis/build/jaagr/polybar/src/main.cpp:71:22: error: incomplete type 'polybar::v3_1_0::connection' named in nested name specifier
connection& conn{connection::make(xcb_connection, xcb_screen)};
^~~~~~~~~~~~
/home/travis/build/jaagr/polybar/include/x11/types.hpp:30:7: note: forward declaration of …
```
=> fix(travis): Crash

README.md
I am also working on a script that fetches all contributors and puts them into a CONTRIBUTORS.md file.
But I'd like to merge this before so that people at least know, who's behind the project and to give props to @Tobaloidee for the logo
=> doc: List main contributors in README

README.md
I missed this when reviewing the README contributor PR, and it's bugging me a lot.
=> fix(README): remove colon between name and username

CMakeLists.txt, cmake/01-core.cmake, cmake/02-opts.cmake
Following [1] to get to this setup.
We setup all the ccache configuration before calling project() because
project will perform compiler checks. This is also why we can't use
message_colored here and print the colors manually
Before ENABLE_CCACHE was not yet defined when we reached the check in
01-core because the option was defined in 02-opts
[1] https://crascit.com/2016/04/09/using-ccache-with-cmake/
=> refactor(ccache): Enable by default

src/modules/bspwm.cpp
I *think* #981 is an issue, but I need someone else to confirm it (both the problem and the fix).
Fixes #981.
=> fix(bspwm): remove monitor focus command

tests/unit_tests/utils/color.cpp, tests/unit_tests/utils/file.cpp, tests/unit_tests/utils/math.cpp, tests/unit_tests/utils/scope.cpp
This converts all legacy tests to use googletest. Except for the string test which was already converted in #1237. I will open a new PR, once this and #1237 are merged to remove the legacy testing functions in `test.hpp`
Closes #127 because we know have a proper testing setup and testing all the things is something we will never achieve so otherwise this issue would just stay open forever
=> Convert tests to gtest

include/adapters/net.hpp, src/adapters/net.cpp, src/modules/network.cpp
This should probably throw network_error instead of call `perror()` maybe?
Also, I think if you lose addressing but the interface is still up, the value on m_status isn't unset so the address is still displayed. I think the IPv4 thingy does that too.
I'm also not sure if this works on FreeBSD.
EDIT: Fixes #1234
=> Teach net module how to query an IPv6 address.

README.md
I have already cleaned up the [Compiling](https://github.com/jaagr/polybar/wiki/Compiling) wiki page and have now also done some cleanup in the README to clarify things a bit.
=> Reorganize build instructions on README

include/modules/mpd.hpp, src/modules/mpd.cpp
The repeatone button doesn't influence repeating behaviour at all, so
the name is misleading.
This deprecates icon-repeatone for now, until we can completely remove
it
Fixes #1279
=> refactor(mpd): Replace icon-repeatone with icon-single

common/travis/tests.sh, include/components/builder.hpp, include/drawtypes/label.hpp, src/CMakeLists.txt, src/components/builder.cpp, src/drawtypes/label.cpp, tests/CMakeLists.txt, tests/unit_tests/components/builder.cpp
As described in #1194 polybar never actually checks the m_ellipsis flag
in labels.
Right now, I have only refactored the builder to determine the actual
label text inside a function and added failing tests for that bug and
the general expected behaviour of get_label_text. This is why the
tests in the current build will fail.
This will probably decrease test coverage quite drastically, as codecov
doesn't track builder.cpp yet, so this basically adds a bunch of not
covered lines that codecov is now tracking
Also @NBonaparte, do you think the builder should throw an exception,
if the maxlen is less than the length of the ellipsis and ellipsis is
enabled, because it would be impossible to follow both the label-maxlen
and the label-ellipsis directive?
EDIT1: Seems like the new test doesn't …
=> fix(builder): Respect label-ellipsis option

README.md, contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD, include/version.hpp
I think the 3.2.0 release is badly needed right now, for one because xcb-proto 1.13 is getting more and more common, making the 'eventstruct' issue (#973) catch on (see #1335, #1330, #1294, #1252, #1233, #1090, #1114) and also 3.1.0 cannot be compiled with gcc 8 without manually updating the i3ipcpp submodule.
The [3.2.0 Milestone](https://github.com/jaagr/polybar/milestone/2) contained quite a few unfinished issues, I have moved almost all of them into the [3.3.0 Milestone](https://github.com/jaagr/polybar/milestone/4) because this release now has some urgency to it.
The only issue I kept was #1194, because there is already a fix for it (#1198), it just needs to be reviewed and merged.
With this release, I'd like to also propose some guidelines on how we do releases. The base idea is …
=> Release 3.2.0

include/drawtypes/label.hpp, src/drawtypes/label.cpp
Fixes https://github.com/jaagr/polybar/issues/1332
=> Zero pad tokens when min spec starts with '0'

src/modules/i3.cpp
This makes polybar play nice with the i3wm feature `workspace_auto_back_and_forth`, and it is harmless when that option isn't set.
=> fix(i3): Send workspace cmd unconditionally on click

src/components/controller.cpp
Prevents creating a window if `--stdout` option is used. 
Fixes #1314.
=> fix(controller): don't draw window if writing to stdout

src/components/builder.cpp, src/drawtypes/label.cpp, src/modules/date.cpp
Trimming the quotes in labels and the date module are not needed at all,
because surrounding quotes are removed when loading the values from the
config.
Removing the quotes in the builder also doesn't seem to serve any
purpose at all.
=> refactor: Remove unnecessary quote trim operations

build.sh
- add option flags;
- among others, flag --auto allows executing
script in a non-interactive mode, where all
unset options are defaulted automaticaly;
- add help/usage;
This allows installing polybar non-interactively from various system scripts, eg users could
`./build.sh --auto --all-features --no-install-config`
Also fixes bug with install prompts - prompt shows default Y (`[Y/n]`), but in reality `Y` is not assigned to $p when no input is given, meaning subsequent ` $p == Y` check fails:
```
read -r -p "$(msg "Execute 'sudo make install'? [Y/n] ")" -n 1 p && echo
[[ "${p^^}" == "Y" ]] && {   # <-- !! $p would be empty if user gave no input !!
sudo make install || msg_err "Failed to install executables..."
}
=> extend build.sh

src/adapters/net_nl.cpp
Don't filter out any character that is not part of the current C locale, since it might drop some wanted characters.
Fixes #1367
=> fix(net): Allow all characters for the SSID

src/components/config.cpp, src/drawtypes/ramp.cpp, src/ipc.cpp, src/x11/cursor.cpp
another option would be
```cpp
if (type == "action" || type == "cmd" || type == "hook") {
return true;
}
return false;
```
=> removes big unused if

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md
With this we *finally* have some issue templates so that we can directly get all the information we need from the user without having to go back and forth.
The feature request template now also puts the burden on the user to make a case why a certain feature should be added. This should help us to more clearly be able to distinguish between features that would fit the project and ones that wouldn't.
Once this is merged, users should see the following dialog when trying to open a new issue, which I think is pretty neat:
=> github: Custom issue templates

include/x11/cursor.hpp
It seems that if you don't have `xcb-xkb` installed, you get a compilation error because `cursor.hpp` uses `map` without `std::` in front of it. When you install `xcb-xkb` back, it includes `x11/extensions/xkb.hpp` which has `using std::map`.
I can reproduce this error on branch 3.2, too.
=> fix(compiling): `map` variable without namespace.

tests/CMakeLists.txt
From commit 880896c6f4814f4c7798355a652dc6167be2b75f in googletest cmake
test configuration fails with errors like
CMake Error: install(EXPORT "gtestConfigInternal" ...) includes target
"gtest" which requires target "i3ipc++" that is not in the export set.
The issue was that link_libraries also affected the googletest internal
targets that came after it making the whole thing fail.
This could also have been solved by moving link_libraries after the
configuration of googletest but according to the cmake documentation [1]
target_link_libraries should be prefered over link_libraries anyways.
[1]: https://cmake.org/cmake/help/latest/command/link_libraries.html
Fixes #1393
=> fix(gtest): prefer target_link_libraries

src/modules/mpd.cpp
Resolves #1399 
This is directly related to #868.
I should note that both this fix as well as #868 result in 
`format-{playing,paused,stopped}` options being ignored if the same `format-online` options have been specified, though I guess it is preferable to config breakage.
Sorry for causing this mess in the first place, my bad.
=> fix(mpd): Get format-online-{prefix,suffix} explicitly (#1399)

src/modules/temperature.cpp
=> refactor(temperature): Do not use 'm_' prefix with local variable

src/modules/cpu.cpp
Resolves #1282 
This pretty much restores the way things were done pre 3292cea where the token splitting shenanigans were introduced.
=> fix(cpu): Replace %percentage-cores% normally

src/adapters/net.cpp
overriding my [old pr](https://github.com/jaagr/polybar/pull/1452) to source from a proper issue branch for [issue 1447](https://github.com/jaagr/polybar/issues/1447)
Replaces old 'caddr_t' type with generic 'char*'
EDIT: Fixes #1447
=> replace caddr_t with char*

src/modules/script.cpp
If a tailed command is used polybar would generate two action tags, one
with %counter% replaced and one with %pid% replaced, but never both
This is a bug that was introduced in #934
=> fix(script): Avoid duplicate action tags for tailed

contrib/polybar.aur/PKGBUILD, include/modules/cpu.hpp, include/version.hpp, src/components/controller.cpp, src/drawtypes/ramp.cpp, src/modules/cpu.cpp, src/modules/i3.cpp
Fixes #1389 
Allows "ramp-padding" in polybar config file to adjust spacing between core loads.
=> Add ramp-padding capabilities to module/cpu

include/modules/cpu.hpp, src/modules/cpu.cpp
Resolves #1389
This just is just the commits in #1472 cherry-picked because the original PR was against `3.2` and contained the 3.2.1 release commit
=> feat(cpu): Add ramp-coreload-spacing (#1472)

build.sh
While working on polybar, I found it super-convenient that the `build.sh` does everything needed to build the project. Back then, I change the script a little to have my preferences automatically as default. With the recent revamp of the build-script, all options became scriptable, so my shell-history was sufficient. One little thing remained, though. The build-directory wanted to be destroyed every time. Since I was in favor of faster feedback, I changed the script a little. Upon further reflection, I think this could even be the default.
This PR accepts a locally existing build-directory. A message is emitted and the '--force' option to remove it is still honored. However, if people want to reuse the build-directory to reduce recompile-times, this gives them the rope they ask for.
What …
=> Accept a locally existing build-directory

src/x11/extensions/xkb.cpp
Fixes #1469
I wasn't sure if I should use std::forward here but decided against it since the function is not templated. rvalue references still give me headaches ^^
=> fix: Move return value of parse_layout_symbol

include/adapters/net.hpp, src/adapters/net.cpp
wireless_tools 29 redefines inline in iwlib.h as:
#define inline inline __attribute__((always_inline))
which conflicts with POLYBAR_NS, which is defined as:
#define POLYBAR_NS    \
namespace polybar { \
inline namespace APP_VERSION_NAMESPACE {
In version 30.pre9 this #define is moved into a source file and thus
cannot conflict.
The error only occurs when building with clang, so it seems gcc and
clang handle this differently
Fixes #1492
=> fix(build): remove side-effects of iwlib.h

include/cairo/font.hpp
If FcNameParse returns NULL FcDefaultSubstitute segfaults
We log and throw an error here because the signal emitter swallows all
exceptions so if that exception was thrown, the bar would stop rendering
without any indication as to why.
Fixes #1435
=> fix(font): Check FcNameParse return value

include/adapters/net.hpp
Missed this in #1493...
`#include "settings.hpp"` should be declared before the `#if WITH_LIBNL` macro, otherwise it isn't defined.
I moved the other includes with it to make it neater.
=> fix(net): make sure WITH_LIBNL is defined before checking

src/components/builder.cpp, src/components/parser.cpp, src/components/renderer.cpp, tests/CMakeLists.txt, tests/unit_tests/components/parser.cpp
The builder::cmd function creates a new action block with a command.
However it fails to escape all colons and only escapes the first colon
~For now I have refactored the code a bit and added failing unit tests to
show the bug. I will implement the proper behaviour in the next few
days (hopefully).
This changes the semantics a bit: We now also escape the escape character so that we get the exact same command back that we put in.~
Fixes #984
=> fix(cmd): Escape all colons in action tag command

.codecov.yml
Most PRs change code where no tests have been written so far and where
adding tests is difficult. Codecov fails all those PRs.
These values should be adjusted once we have better integrated testing
into our workflow and have written better testing infrastructure for
modules and very tightly coupled components
=> coverage: Allow small drops in coverage

include/components/renderer.hpp, include/x11/background_manager.hpp, include/x11/tray_manager.hpp, src/components/renderer.cpp, src/x11/background_manager.cpp, src/x11/tray_manager.cpp
This patch adds support for observing multiple slices of the desktop background.
This is used for the tray so that it doesn't have to rely on the bar's rect to
get the desktop background. In particular, it now handles the case where the
tray is not contained fully within the bar's outer rect (for example, when using tray-offset-{x,y})
=> tray: correctly handle transparency when using offset

.github/ISSUE_TEMPLATE/bug_report.md
Often it would be useful to know if something broke after an update or
if the bug was there from the beginning
=> github: Ask about regressions in bug reports

README.md, contrib/polybar.aur/PKGBUILD
Since v3.1.0 we provide a tarball containing the repo and all submodules. This Adds documentation and changes the AUR PKGBUILD to use those archives. It's much easier for the users to not have to deal with git as well, it also saves time because cloning the repo is quite slow
=> Build releases with release tar ball

include/modules/bspwm.hpp, src/modules/bspwm.cpp
This adds a new label in the bspwm module `label-marked`
This flag for focused nodes of a focused desktop was introduced earlier this year
and released with bspwm 0.9.4
It adds the `M` flag to `G` type items in bspwm's report format
Resolves #1552
Ref: https://github.com/baskerville/bspwm/commit/d0138af475541732d3f2ae25dff558c07062e24f
=> feat(bspwm): Support marked flag for focused nodes

.travis.yml, common/travis/environment.sh
This travis environment contains more up-to-date versions of clang and
gcc (namely 7.0.0 and 5.4.0). This allows us to remove all the code used
to get those newer versions in trusty.
Ref: https://docs.travis-ci.com/user/reference/xenial/
=> travis: Upgrade to xenial

include/components/types.hpp, include/x11/extensions/randr.hpp, src/components/bar.cpp, src/modules/xbacklight.cpp, src/x11/extensions/randr.cpp
~randr_output::match would match regardless of if there is a dash in the
monitor name.
This was done because jaagr's monitors didn't have a dash in them
depending on the graphics driver used. This behavior was introduced in
[1].~
~This behavior creates issues in situations where a user has a monitor
with a dash in its name and one without e.g. HDMI-2 and HDMI2 (see
#1532). In both cases polybar would be loaded on monitor HDMI2.~
~Monitor name matching should always be strict~
~[1]: 4d7f6c14e65332793e313866ba05539d3776cf65~
EDIT: This now introduces `monitor-exact` in the bar section which defaults to true and if set to false does fuzzy monitor matching (ignores dashes in monitor names).
It also removes `monitor-strict` from the xbacklight module and uses `monitor-strict` from the bar …
=> fix: strict monitor name matching

include/modules/meta/base.hpp, src/modules/meta/base.cpp, src/modules/mpd.cpp
Closing the oldest open issue. Not really anything groundbreaking in there. The changes to the mpd module are needed because of the fix for property inheritance for mpd in #868.
I used the following config to quickly test this feature.
```dosini
[bar/example]
font-0 = Noto Sans Mono:style=Regular:size=12
font-1 = Noto Sans Mono:style=Regular:size=22
modules-left = text text2
[module/text]
type = custom/text
content = Text %{T1} small
content-font = 2
[module/text2]
type = custom/text
content = Text small
```
Resolves #19
=> feat: format-font

include/modules/fs.hpp, src/modules/fs.cpp
Seems this was missed in a682d2af91881fa775e265520f7f820cb71dc707
This is now also consistent with what df does
Closes #743
=> fix(fs): Calculate free bytes properly

src/modules/memory.cpp
As requested in #1598
Two decimal places for megabytes gives you precision at the scale of tenths of kilobytes, which is quite unnecessary for RAM
=> memory: Remove decimal places for megabytes

src/adapters/net.cpp, src/modules/network.cpp
If you have `accumulate-stats = true` it is useful to be able to display
the current network speed even if the interface is disconnected.
This was suggested by @dkasak in #339
=> feat(net): All tokens for all labels

src/x11/extensions/randr.cpp
primary_info.name() throws an error if get_output_info is called with
XCB_NONE
Fixes #1620
=> fix(randr): Check if there is a primary monitor

include/events/signal_emitter.hpp
If any signal receiver throws an exception for any reason after
receiving a signal, no one would find out about it because the signal
emitter just ignored exceptions
Also actually delivering the signal caused some exceptions because not
all signals have a receiver.
I hope this doesn't bring too many polybar errors to light that were swallowed before
Resolves #1593
=> signal_emitter: Don't swallow exceptions

tests/unit_tests/components/bar.cpp, tests/unit_tests/components/builder.cpp, tests/unit_tests/components/parser.cpp
The `INSTANTIATE_TEST_CASE_P` macro when used with zero variadic arguments required a comma after the last argument to not generate any warnings, now it generates errors when there is a comma.
=> Test compilation fails again

README.md
IF you isntall via a package manager, it's a bit trickier to get the default config, I found myself reading the sourcecode for the makefile to figure out where it came from.
On arch, at least, a copy is stored in `/usr/share/doc/polybar/config`, I assume this is the same for most distros, so I figured i'd add that snippet to the readme
=> Update readme on installing example config

include/modules/xkeyboard.hpp, include/x11/extensions/xkb.hpp, src/modules/xkeyboard.cpp, src/x11/extensions/xkb.cpp
TEAM EDIT: Fixes #1558 
Closes #1048 
**Changelog Notes:**
This deprecates `label-indicator` in favor of `label-indicator-on`
=> Added an option to replace xkb indicator names

include/x11/tray_client.hpp
This PR fixes #1674 by removing the copy ctor and assignment operator of `tray_client`.
Copy assignment was marked as defaulted however as stated in the C++ standard:
> A defaulted copy/move assignment operator for class X is defined as deleted if X has:
> - […]
> -  non-static data member of reference type, or
> - […]
>
> § 12.8
Since a reference can't be reassigned, I just marked this operator as explicitly deleted.
The copy ctor was also defaulted and it is well-formed but the dtor unembed the window so copying that class may cause bugs, so I also marked it as explicitly deleted. Another solution if copying this class is needed is to do the "unembeding" in a custom deleter of `m_xembed`.
=> Fix compilation with clang8 #1674

src/components/controller.cpp
Fix #428.
To fix this bug, I chose to ignore signals in the handler if polybar is being killed/reloaded.
Moreover to avoid polybar from being killed by `SIGUSR1` during reloading, `SIGUSR1` is ignored until the signal is registered in the new polybar process.
As stated in `signal(7)` man page, the ignored signals are still ignored after a call to a function of the execvX family. 
> During an execve(2), the dispositions of handled signals are reset to the default;
the dispositions of ignored signals are left unchanged.
=> fix(controller): ignore SIGUSR1 until polybar is fully reloaded.

.github/ISSUE_TEMPLATE/bug_report.md, README.md, SUPPORT.md
With this I want to try to get fewer questions and tech support issues in our issue tracker. This will help us focus more on the actual issues.
The idea is get the community to reddit and irc for discussions and questions and have this repo be more focused on code.
To monitor new questions on those platforms, I suggest all of us core devs monitor the following places for new questions:
* [1]: For any posts mentioning polybar on reddit
* [2]: The rss feed of the r/polybar subreddit
* [3]: For all stackexchange questions mentioning polybar. Note this list cannot be sorted by date and new results may show up only after a few days.
* [4]: For all unix.stackexchange.com questions mentioning polybar. This list is sorted by date.
I have also created a github saved reply for closing issues that …
=> Shift over question and help issues over to irc, reddit, and stackexchange

src/modules/fs.cpp
Cast before calculate to avoid overflow.
Fixes #743
=> fs: Fix incorrect size report on 32bit machines

include/utils/math.hpp, src/x11/tray_manager.cpp
As reported in #1666, negative percentage in tray are ignored.
It seems that the function (```percentage_to_value```) used to compute the value from the percentage clamps the value between ```0``` and ```max_value```.
To fix this problem, I added a ```signed_percentage_to_value``` function which clamps the value between ```-max_value``` and ```max_value``` and so it allows percentage between -100% and 100%.
However, when I fixed this bug, I noticed something strange, is it okay that the bar stops where the tray is supposed to be without any offset (see image below)?
In the wiki it is written that only the content should be shifted, so I wonder if this is a bug.
Minimal config:
```
[bar/example]
width = 100%
height = 27
font-0 = fixed:pixelsize=10;1
font-1 = …
```
=> Fix tray offset #1666

contrib/polybar-git.aur/PKGBUILD
The polybar-git PKGBUILD should not be updated for patch releases
=> fix(aur): Patch release in polybar-git package

include/CMakeLists.txt
This PR is a proposition to move auto-generated files in build directory.
The problem with generating sources in sources directories is that it may cause problem when the compilation mode (Release; Debug; …) is changed without cleaning.
Furthermore, some IDEs that support CMake create a build directory per compilation mode, so the project directory has the following architecture:
```
|─ debug-build/
|─ release-build/
|─ include/
|─ setting.hpp
|─ setting.hpp.cmake
```
With generated sources in the sources directories when I change from Debug to Release, cmake doesn't regenerate the setting file since it already exists but if you move the generated files in the build directory the problem disappears.
```
|─ debug-build/
|─ generated-sources/
|─ setting.hpp
|─ release-build/
|─ …
```
=> CMake improvement (moving generated sources out of sources directories)

cmake/02-opts.cmake
Fix #1180.
As the kernel documentation said:
https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-backlight
>  This file will also show the brightness level stored in the driver, which may not be the actual brightness (see actual_brightness).
Therefore the brightness value should be read in the `actual_brightness` file.
=> fix(brightness): reading brightness in actual_brightness

include/x11/window.hpp, src/x11/window.cpp
Fixes #1728.
Add default copy constructor whose implicit generation is deprecated by C++ standard.
I also remove the `window& operator=(const xcb_window_t win);` operator that seems to be useless.
https://github.com/jaagr/polybar/blob/7d0c6300f6d63eb018b842d122b98fb7c4efbaef/src/x11/window.cpp#L10-L13
If I am not wrong this `operator=` constructs an `resource` object which is destroyed immediately so this is useless.
This PR also depend on a PR on xpp (https://github.com/jaagr/xpp/pull/16)
=> Fix compilation under gcc 9

include/modules/temperature.hpp, src/modules/temperature.cpp
add configuration `base_temperature` to make it easy to set ramp icons.
resolves #1703
TEAM EDIT: Documentation:
```dosini
; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20
; Requires the <ramp> tag
; The icon selection will range from `base-temperature` to `warn-temperature`,
; temperatures above `warn-temperature` will use the last icon
; and temperatures below `base-temperature` will use `ramp-0`
ramp-0 = A
ramp-1 = B
ramp-2 = C
ramp-foreground = #55
```
=> Improve temperature ramp configuration

include/CMakeLists.txt, include/settings.hpp.cmake
Bothered me for quite some time that `polybar -vvv` doesn't actually print the effective flags used
=> build: Add build type specific flags to -vvv

include/cairo/context.hpp
* Initialize unsigned int matches to 0 for Fedora 30
=> fix: Fix #1758

include/modules/battery.hpp, src/modules/battery.cpp
Following the discussion on #1753, this PR adds `%percentage_raw%` to the battery module, which represent the real percentage reported by the kernel regardless of the value set in the `full-at` property by the user. This property still sets the state as *Full* when the percentage level goes above its value. The behavior of the `%percentage%` token has not been altered.
Since in the next major (breaking) release the plan is to bring this behavior to the `%percentage%` token, the code has been refactored towards this deprecation of this old behavior, storing the real percentage instead of the clamped one and adding a clamping function for that purpose.
Feedback and comments are welcome.
=> battery: add `%percentage_raw%` token, which is not forced to `100` when real percentage is above `full-at`

src/adapters/pulseaudio.cpp
Previously, when volume was in close proximity to n_max_volume, a larger
increase would not do anything. After this patch, volume is set to
m_max_volume in such scenarios. If the volume already is at
n_max_volume, we mirror the old behavior and emit a warning.
So, for example, consider m_max_volume was 100%, but the volume prior
to the increase was 96%. An increase of 5% would do nothing (emit a
warning, even) instead of setting the volume to 100%.
Note that this might happen even if the volume is at 95% according to
%percentage% due to rounding errors.
=> Set volume to m_max_volume when the increase was too huge

CMakeLists.txt, include/common.hpp, include/settings.hpp.cmake
I don't know the original intention behind this but it clutters up debug
traces and basically makes ccache useless.
The only benefit it has, giving version info in stacktraces, is kind of
void since we already ask for version information on github issues.
=> refactor(build): Remove version number namespace

cmake/02-opts.cmake, include/settings.hpp.cmake
As stated in the documentation of set (https://cmake.org/cmake/help/latest/command/set.html), `INTEGER` type doesn't exist.
`STRING` type is now used and a check has been added.
This PR removes the following warnings:
```
CMake Warning (dev) at cmake/02-opts.cmake:90 (set):
implicitly converting 'INTEGER' to 'STRING' type.
CMake Warning (dev) at cmake/02-opts.cmake:91 (set):
implicitly converting 'INTEGER' to 'STRING' type.
```
CMake version: 3.14.3
=> Remove warnings in cmake

doc/conf.py
@APP_VERSION@ isn't available on rtd because it doesn't configure the
entire project
=> rtd: Use provided version string on rtd

config.cmake
This confuses lots of people when removing the bspwm module from the
sample config and trying to use the i3 module
=> config: Remove bspwm variable references

include/cairo/font.hpp
Originally the size function returned the scaled `size` property for
scalable fonts and the non-scaled `pixelsize` property for non-scalable
fonts. This caused lots of issues when that property was 0 (empty bars,
characters not drawn without warning, see references at the bottom).
This behavior was mostly observed on debian where `size` is set to 0 if
`pixelsize` is set.
We now try to use both properties for both types, but prefering `size`
for scalable fonts and `pixelsize` for non-scalable ones.
This behavior doesn't break existing correct behavior but now never
returns 0. It will always try to fall back to the other property or to
some fallback value if both properties are 0.
I originally thought this could also make font patterns more expressive
by being able to specify the size of …
=> refactor(font): More robust font size calculation

include/modules/i3.hpp, src/modules/i3.cpp
Like when i3-msg is used (`i3-msg workspace '","'`), the name of the workspaces need to be surrounded by quotes to accept all strings.
Fixes #1797.
=> fix(i3): workspace name need to be surrounded by quotes to accept all strings

src/ipc.cpp
This PR change `polybar-msg` to output messages to stdout when the exit code is 0.
Currently wanting to only log errors coming from `polybar-msg` is very akward and non-unixy, to do so one is forced to write something like the following:
``` sh
err=$(polybar-msg hook module 1 2>&1) || echo "$err"`
polybar-msg hook module 1 2>&1 | awk '!/Successfully wrote/ {print $0}'
```
With this change you can apply the conventional redirection pattern:
```sh
polybar-msg hook module 1 1>/dev/null
```
In my case not redirecting successful output result in a flood of the logs of ~10k message a day.
=> fix(msg): use stdout when exiting with code 0

CMakeLists.txt, cmake/01-core.cmake, cmake/05-summary.cmake, contrib/bash/CMakeLists.txt, contrib/zsh/CMakeLists.txt, doc/CMakeLists.txt
This change should be a no-op in the normal case and at the same time make it
easier to customise polybar builds on systems with special needs.
=> Use GNUInstallDirs instead of hardcoded paths

include/components/config.hpp
There is also a lot of refactoring that could be done here but since we are rewriting parts of the config parser already we'll do it there.
=> fix(config): Allow empty string as ref fallback

include/modules/github.hpp, src/modules/github.cpp
Add support for github enterprise with a new key `api-url`.
This feature needs to be checked properly since I don't have access to the github of an entreprise.
I just checked that it works correctly with `github.com`.
Closes #1812.
=> feat(github): add support for github enterprise

include/components/config.hpp, include/components/config_parser.hpp, include/utils/string.hpp, src/components/config.cpp, src/components/config_parser.cpp, src/main.cpp, src/utils/string.cpp, tests/CMakeLists.txt, tests/unit_tests/components/config_parser.cpp, tests/unit_tests/utils/string.cpp
This is the next step to merge #1237 in stages.
Currently there are barely any restrictions on how the config can be
written. This causes things like config files with DOS line endings to
not be parsed properly (#1366) because polybar splits by `\n` and when
parsing section headers, it can't deal with the `\r` at the end of the
line and thus doesn't recognize any section headers.
With this PR we introduce some rules as to what characters are allowed
in section names and keys.
Note: When talking about spaces I refer to any character for which
`isspace()` returns `true`.
The rules are as follows:
* A section name or a key name cannot contain any spaces as well as any
of there characters:`"'=;#[](){}:.$\%`
* Spaces at the beginning and end of lines are always ignored when
parsing
* Comment …
=> config_parser: Introduce stricter syntax conventions

include/modules/meta/base.inl
Adding the reset tag to empty modules makes polybar add margins and
separators for that empty module.
Fixes #1857
Ref #1596
=> fix(modules): Only add reset tag on non-empty modules

contrib/polybar.aur/PKGBUILD
People without sphinx installed couldn't actually build the AUR package.
=> fix(aur): Add sphinx as a build dependency

src/utils/file.cpp
This fixes a regression introduced in
56e24992dfe2fba32b1f6b07fc37ab7d0a7c6aba where relative config file
paths weren't recognized because file_util::expand just added a slash
to the beginning.
That is calling `polybar -c config example` would try to load the config
file at `/config` instead of using the relative path as before.
In all other cases where expand is used this change shouldn't matter
because polybar only accepts absolute paths everyhwere else.
Theoretically this would now allow relative paths (relative to the cwd
where polybar was called) but this shouldn't used (or documented)
because that behavior will change when merging #1523 which would make
paths relative to the polybar config.
Ref #1523
Ref 56e24992dfe2fba32b1f6b07fc37ab7d0a7c6aba
=> fix(file): Don't add slash to relative path

README.md
I added the repo to code triage to get regular mails about open issues of polybar. Since I cannot program C++ well, I can maybe help better by reviewing issues. Maybe other people can and want to do the same. After all, polybar has many users who know about its configuration and such.
If you choose to decline this PR, I just get mails. If you choose to accept it, maybe some people are attracted to help out with the triage part of issues. At the very least, it is another nice-looking badge on the README and I heard that is the latest craze among the kids these days. :smile:
=> Add Code Triage-Badge

src/components/bar.cpp
While an update was forced whenever polybar was made visible, the
`m_lastinput` variable was still set to the same value as when the bar
became hidden because updates to it were prevented.
Fixes #1875
=> fix(ipc): Update bar when making bar visible

include/adapters/pulseaudio.hpp, include/modules/pulseaudio.hpp, src/adapters/pulseaudio.cpp, src/modules/pulseaudio.cpp
Add ` %decibels%` token in pulseaudio module.
Implements #1886.
Tested on two archlinux devices and everything seems fine.
=> feat(pulse): Show volume in decibels

src/modules/temperature.cpp
Given `warn-temperature = 75`, The style should be changed to the warning variant _at_ `75` rather than _after_.
=> Warning style on temperature should be inclusive

include/components/controller.hpp, src/components/controller.cpp
You can't use the same name twice inside the module lists
E.g.
```dosini
modules-left = a b c
modules-center = a
modules-right = b
```
would print an error.
We only print an error for now because we don't want to break existing
configs. But in the future this should be properly enforced.
This is in preparation for fixing #1172, because I plan on making modules uniquely identifiable by their name.
=> controller: Print error for duplicate modules

include/components/bar.hpp, src/components/bar.cpp
Some WMs like i3 discard position information when unmapping the bar and
because of that the bar would be at the wrong position after being
remapped.
Fixes #1484
Ref: https://github.com/i3/i3/pull/3834
=> fix(bar): Configure position before remapping

README.md, contrib/polybar-git.aur/PKGBUILD
Ref: https://github.com/polybar/xpp/pull/17
Fixes #1892
**Release notes:** All mentions of python2 can be removed from the wiki.
The `polybar` `PKGBUILD` can be updated.
=> build: drop python2

include/components/builder.hpp, include/components/types.hpp, include/drawtypes/label.hpp, include/drawtypes/progressbar.hpp, include/modules/meta/base.hpp, src/components/bar.cpp, src/components/controller.cpp
Some people use text modules instead of the `separator` key in the bar
section to better configure the separator (colors, fonts). Since we
disallowed the same module being used multiple times in #1534, this will
now print an error message.
This should help with this a bit.
Ref #1913
=> bar: Make module separator a label

include/components/ipc.hpp, include/modules/ipc.hpp, include/settings.hpp.cmake, src/CMakeLists.txt, src/components/ipc.cpp, src/settings.cpp.cmake, src/utils/http.cpp
Since APP_VERSION is different for every commit and almost all file
include settings.hpp, the whole project has to be rebuilt for every
commit. With this, hopefully, this can be greatly reduced and only
changed files need to be rebuilt. This will also help ccache
=> build: Move non-macro variables into settings.cpp

.github/ISSUE_TEMPLATE/config.yml
This is yet another way to steer people towards reddit for questions
instead of using the github issue tracker
Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
In the end the issue chooser will look something like this:
=> github: Add subreddit as contact link

.travis.yml, README.md, SUPPORT.md, doc/index.rst
The Gitter room https://gitter.im/polybar/polybar should serve a similar
purpose as the IRC room with the benefit that messages persist and can
be received when offline.
From now on gitter should be the place where the polybar community
lives. Reddit is great for asking longer questions in the style of a
forum but not so great for quick back and forth conversations. IRC is
better in that aspect but has the serious downside that you have to stay
connected to get an answer and messages are not logged (only by your
client).
Both reddit and IRC are here to stay and I will still check them
regularly, but we should encourage people to join gitter.
=> doc: Add Gitter room

src/modules/pulseaudio.cpp
This PR adds a config option to specify a control panel for pulseaudio.  The default is pavucontrol.
It also listens for right-click events and uses command_util to launch the specified control panel.
=> Feature pulseaudio controlplanel

include/components/builder.hpp, src/components/builder.cpp
the `node` and `node_repeat` were never called with the optional
parameter add_space. And its default value is false, so the
corresponding code was never used.
I think in general it is better to just have the user of those functions
call `builder::space` when they need to instead of adding more
complexity to the `node*` functions.
=> refactor(builder): Remove unused add_space parameter

src/components/controller.cpp
This fixes the below error:
/code/polybar/src/components/controller.cpp:110:117:   required from here
/code/polybar/src/components/controller.cpp:100:60: error: passing ‘const volatile std::shared_ptr<polybar::modules::module_interface>’ as ‘this’ argument discards qualifiers [-fpermissive]
auto equal_predicate = [](auto& m1, auto& m2) { return m1->name() == m2->name(); };
=> Fix controller.cpp compilation on GCC 6.3

include/modules/cpu.hpp, src/modules/cpu.cpp
In a virtualized environment (e.g., Chrome OS), steal time can be non-negligible. This PR fixes an issue where the machine can be entirely (100% across all cores according to htop) busy, but polybar reports only 30-40% load.
=> Consider steal time in CPU load calculation

include/components/builder.hpp, src/components/builder.cpp
Same as in #1952, the methods are never called with the optional
parameter, except once where it is called with the default value.
Ref: #1952
=> refactor(builder): Remove unused condition parameter

include/cairo/context.hpp, src/components/renderer.cpp
I finally found the issue in https://github.com/polybar/polybar/issues/591!!
Turns out it wasn't the tray code but the code that calculates the block positions. It didn't work when the center block was empty and the right block grew too large (with `fixed-center = true`).
There were also some bugs with `fixed-center` which basically made `fixed-center = true` not work reliably if the right block was too large. I basically rewrote the entire logic there.
The definition of what `fixed-center` exactly does wasn't really clear as well and since the code was full of bugs, I found it hard to figure out what the intention was. Here is what I came up with:
* `fixed-center = true`: The center block stays at the center of the bar
whenever possible. It can be pushed to the left if the right block …
=> Renderer alignment fixes

contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD
xorgproto always was a make dependency (I think) but it was
automatically included indirectly by another dependency.
Arch recently cleaned up some xorg related packages which made xorgproto
no longer an indirect dependency of polybar which spams cmake with
messages like:
```
Package 'xproto', required by 'xau', not found
Package 'xproto', required by 'xdmcp', not found
Package 'xproto', required by 'xau', not found
Package 'xproto', required by 'xdmcp', not found
Package 'xproto', required by 'xau', not found
Package 'xproto', required by 'xdmcp', not found
Package 'xproto', required by 'xau', not found
Package 'xproto', required by 'xdmcp', not found
```
And during `make` finally completely fails the build because some
library's include directories are not honored because the xproto.pc …
=> fix(aur): Add xorgproto package as make dependency

src/modules/ipc.cpp
Before, if the command produced no output, the `m_output` field would
not have been overwritten and the old output was displayed.
But since this is an explicit trigger of the hook, the user would expect
the output to be updated to whatever the script produces (even if that
is nothing).
Ref: https://www.reddit.com/r/Polybar/comments/e9a8ww
=> fix(ipc): Clear content if no output is produced

contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD
Reverts polybar/polybar#1962
Some things were reverted on the Arch side, so this issue no longer occurs. Polybar doesn't directly depend on `xorgproto`, only its dependencies need the `.pc` files provided by `xorgproto`. So we really shouldn't have it in the `makedepends`.
Ref: https://lists.archlinux.org/pipermail/arch-dev-public/2019-December/029767.html
=> Revert "fix(aur): Add xorgproto package as make dependency"

include/errors.hpp
This is dependent on a PR to xpp that does the same. Newer compilers
(GCC10 in particular) are stricter about which headers provide the
std exception types.
=> Add missing <stdexcept> header

include/cairo/context.hpp
As suggested by @kronn (#1959)
This is a slightly modified patch introduced by @ayosec in their repo
for packaging polybar .deb packages.
Ref: https://github.com/ayosec/polybar-debian
Ref: https://github.com/ayosec/polybar-debian/blob/master/patches/0001-Show-full-contents-when-an-unmatched-character-is-fo.patch
=> font: Show context in unmatched character warning

src/components/controller.cpp
Functionality-wise reverts the changes from #1534
In #1907 we have decided to allow the same module to appear multiple
times (and deliver actions to all matching modules). But since that PR
will likely take longer to get merged, I want to remove the error from
polybar because the message it prints isn't really true anymore.
=> controller: Stop printing errors for non-unique modules

src/adapters/net.cpp
Before tuntap devices would never call the generic `network::query`
method and just return true.
Fixes #1986
=> fix(net): Query IP addresses for tun/ tap devices

tests/CMakeLists.txt.in
In master gtest fails to build with the error
/home/travis/build/polybar/polybar/build/googletest-src/googlemock/include/gmock/gmock-more-actions.h:138:1: error: ISO C++11 requires at least one argument for the "..." in a variadic macro [-Werror]
ACTION_P(ReturnPointee, pointer) { return *pointer; }
We had a lot of failed builds because gtest often breaks stuff in
master. From now on we will just use a release tag. Whenever there is a
new release, we manually update this file.
Ref: google/googletest#2678
=> fix(test): Gtest compilation failure

include/drawtypes/animation.hpp, src/drawtypes/animation.cpp, src/modules/battery.cpp, src/modules/network.cpp
Fix #568.
As it may be seen in the code, the animation need to be synchronized with the thread that calls the `broadcast` function in order to keep a stable framerate.
To synchronize the thread and the animation, I moved the "animation update" in the `subthread` method.
Although this fix the bug, I don't like to move the "animation update" responsibility to another class. The modules should not have to update the animation. Moreover it could be easy to forget the call to `increment` that updates the animation. (when the code is refactored or simply when a new module will need this class).
This is why I also implemented a version with an `animation_manager`, but since this is a big refactor, I put this version in another branch.
=> …
=> Fix animation framerate

include/components/logger.hpp, src/components/logger.cpp, src/modules/fs.cpp
Use const ref and universal references to avoid to copy a lot of strings especially when the function is "disabled" (like `trace_x`).
=> cleanup(logger): use universal references to avoid useless copies

src/modules/xworkspaces.cpp
In the case where _NET_NUMBER_OF_DESKTOPS > |_NET_DESKTOP_NAMES|
the last branch of the get_desktop_names method would return a vector
with _NET_NUMBER_OF_DESKTOPS + 1 elements because we iterate until
_NET_NUMBER_OF_DESKTOPS + 1.
Fixes #1983
=> fix(xworkspaces): Show _NET_NUMBER_OF_DESKTOPS desktops

include/modules/github.hpp, src/modules/github.cpp
Fixes #1815.
Should resolve the segfault issue with #910. The defaults are such that if offline the module displays `Offline` instead of the current `Notifications: -1`. Notifications are still set to -1 and a flag is set to indicate online/offline status which causes `format-offline` to be used when offline.
I haven't tested exhaustively but everything seemed to be working with a couple different configs on my machine.
MAINTAINER EDIT:
Closes #910
=> feat(github): offline label & fixes

.travis.yml
With this we no longer distribute the jsoncpp 1.7.7 source with polybar.
It is possible that polybar will no longer build on older systems that
have an ancient version of jsoncpp (>= 5 years).
Ref: polybar/i3ipcpp#9
=> build: Update i3ipcpp submodule

include/utils/file.hpp, src/main.cpp, src/utils/file.cpp
**Description**
Today when polybar start it does the following configuration search:
1.  ` -c/--config ` parameter
2. `$XDG_CONFIG_HOME/polybar/config` , if the variable is set
3. `$HOME/polybar/config` , if the variable is set
4. Throw error
But it doesn't check if the file exists, this pull request solves that, so the new configuration search is:
1.  `-c/--config`  parameter (if specified)
2. `$XDG_CONFIG_HOME/polybar/config` , if the file exists (variable still being checked)
3. `$HOME/.config/polybar/config` , if the file exists (variable still being checked)
4. Throw error
**Solves**
This PR closes the issue [2016](https://github.com/polybar/polybar/issues/2016), this issue also ask for a change that makes a lot of sense but it'd be another PR:
move the example of config file from …
=> Checks if the configuration file exists

include/modules/github.hpp, include/utils/http.hpp, src/modules/github.cpp, src/utils/http.cpp
**Description** 
The github module only authenticate by query string, and this method is deprecated:
https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters
There is no reason to remove it before the method stop working, so I've made possible to the user choose which authentication method he will use:
* The parameter token remain unchanged.
* If the parameter user is passed then the module will use the not deprecated method, passing user and token on the body of the requisition. Otherwise the module will use the deprecated method.
PS: Some of the files that I've worked on this PR was not on Polybar code style, and that makes some style updates.
**Solves**
This PR closes the issue …
=> Update GitHub API deprecating authentication

contrib/bash/polybar, contrib/zsh/_polybar, doc/man/polybar.1.rst, include/components/screen.hpp, include/x11/extensions/randr.hpp, src/components/bar.cpp, src/components/screen.cpp, src/main.cpp, src/modules/xbacklight.cpp, src/x11/extensions/randr.cpp
When a monitor is connected which is automatically mirrored polybar can crash when the monitor name it is currently running gets removed in `get_monitors` (see #1191).
This also adds a new commandline argument `-M --list-all-monitors` that also lists cloned monitors. I couldn't change the behavior of `-m` since some people rely on `polybar -m` to display polybar on all monitors.
~I have not tested this yet but I will once I get some time at home.~
This also fixes the bugged clone removal code.
Fixes #1191
Fixes #1794
=> fix: Only remove cloned monitors when necessary

include/modules/xworkspaces.hpp, include/x11/extensions/randr.hpp, src/modules/xworkspaces.cpp, src/x11/extensions/randr.cpp
Before the module would just try to evenly distribute desktops
(workspaces) among the viewports.
But since `_NET_DESKTOP_VIEWPORT` actually maps desktops to viewports,
we can use that information to assign workspaces to the right viewport.
I wasn't able to test this yet since I don't have access to my multimonitor setup right now.
Fixes #1849
Fixes #1764
=> fix(xworkspaces): Assign desktops to correct viewport

include/components/controller.hpp, include/components/types.hpp, include/modules/script.hpp, include/utils/command.hpp, include/utils/process.hpp, src/adapters/net.cpp, src/components/controller.cpp, src/modules/ipc.cpp, src/modules/script.cpp, src/utils/command.cpp, src/utils/process.cpp, tests/CMakeLists.txt, tests/unit_tests/utils/command.cpp, tests/unit_tests/utils/file.cpp
Fix #916.
As I said in #916, the bug was:
1.    The child replaces STDIN, STDERR and STDOUT by the pipe.
2.    The child closes the unused pipes
3.    Since the command (`cmd &`) does a fork the `wait` function returns immediately while the process is still alive.
4.    The destructor of the command closes the pipe (parent side)
5.    The new process writes into STDOUT (alias the closed pipe)
6.    The new process get a SIGPIPE and is killed.
I modified the class command, to create "two classes", one that redirects the output with pipes, and one that doesn't redirect output.
I refactored the rest of the code in consequence.
EDIT: At the moment, users still need to use `cmd &` to avoid blocking polybar. It may be interesting to add a parameter to the constructor to detach the child.
EDIT: …
=> Fix broken pipe in command

include/utils/socket.hpp, version.txt
Fixes: GCC 10 Compilation (#2098), see #2097
EDIT: The draft for the github release is [here](https://github.com/polybar/polybar/releases/tag/untagged-0872a2a0acf42997f414)
I have only put this fix into the release because it gets more and more cumbersome to backport fixes into the release branch, the more fixes there are. We should release 3.5.0 fairly soon and then switch to a new branching model ASAP.
=> Release 3.4.3

src/modules/menu.cpp
There was missing some spacing between item+separator in my menu using `expand-right=false`.
Thought this would be a great opportunity for first-time pull-request.
Searching for 'menu' in the issues-tracker reveals no pertinent issues to me.
In this image, you can see the missing spacing between my the 'reboot' label and its separator in the top-right. I've fixed this behaviour, and it works regardless of `expand-right=true` or `expand-right=false`
=> Fixed minor menu item-spacing issue

include/components/controller.hpp, src/components/controller.cpp
If an input is enqueued as a response to an input, the new input will be
swallowed because it will likely be enqueued less than 30ms after the
original event.
This is not something that is an issue right now but it is required to
finish #1907 where, in order to close the menu after a click, the menu
module gets an exec action that closes the menu and adds a command to
the event queue.
The setting also isn't too useful since it will just break polybar input
handling if inputs arrive too fast instead of (possibly) slowing down
the bar.
=> refactor: Deprecate throttle-input-for setting

src/modules/backlight.cpp
Some devices can have "amdgpu_bl1" or "amdgpu_bl2", but the code hardcoded in the value "amdgpu_bl0". This change tests based on the first characters: "amdgpu_bl".
=> Change "amdgpu_bl0" so the "0" isn't hardcoded in

src/modules/battery.cpp
In my opinion, the `full-at` option should take priority over the charging state of the battery.
Especially if the charging state might be corrupted.
Closes #1622 (issue for Thinkpad laptops)
=> Prioritize battery full-at over state

include/modules/meta/base.hpp, include/modules/meta/base.inl, include/modules/meta/timer_module.hpp
Any timer_module based module would sleep for the set interval and then
continue running. Depending on the start time of polybar this
sleep pattern might not be aligned, which causes such modules to always
update in a shifted manner.
Consider the date module as an example. If the update interval is set to
60 seconds and polybar was started at 13:37:37, polybar would update the
clock at 13:38:37, 13:39:37 and so on.
To make matters worse, if a module would perform lengthy checks this
interval might drift over time, causing even more inconsistent updating.
This patch extends the base module with a sleep_until method that calls
the corresponding function on the sleephandler. Additionally the
timer_module is extended to compute the remaining time until the next
interval passes and sleep …
=> fix(timer_module): sleep until next full interval

.clang-tidy
This disables clang-tidy's modernize-use-trailing-return-type warning.
=> Disable modernize-use-trailing-return-type warning

.travis.yml, doc/CMakeLists.txt
If we build only the documentation by invoking `cmake` on the `doc`
folder, the `SPHINX_BUILD` variable is not set and instead of
```
sphinx-build -b html ...
```
it will just execute
```
-b html ...
```
This produces an error but doesn't fail the build because apparently if
the command starts with a dash an error is non-fatal.
Fixes #2191
=> fix(doc): Set SPHINX_BUILD in standalone doc builds

include/utils/file.hpp, src/components/config_parser.cpp, src/utils/file.cpp
Adds `include-directory` keyword which receives as an argument a path to a directory. This keyword allows the importing of all regular files included in the given directory.
```
include-directory = /path/to/directory
```
Closes #1946
=> Add support for keyword include-directory

include/drawtypes/ramp.hpp, src/drawtypes/ramp.cpp, src/modules/temperature.cpp
**Expected behavior**
In the Temperature module [documentation](https://github.com/polybar/polybar/wiki/Module:-temperature), the ramp settings says:
> The icon selection will range from `base-temperature` to `warn-temperature`,
> temperatures above `warn-temperature` will use the last icon
> and temperatures below `base-temperature` will use `ramp-0`
This leads the user to think that the last icon is _only_ used for temperatures above warn-temperature, and likewise ramp-0 for temperatures below base-temperature.
**Actual behavior**
The the last icon is actually used for temperatures slightly below warn-temperature, and ramp-0 for temperatures slightly above base-temperature. This disrupts the style of the module ([example](https://imgur.com/a/IX9kKIQ)).
Using this module and …
=> Temperature module, ramp drawstyle uses wrong icon for temperatures near base and warn temperatures

src/adapters/net.cpp
Before the time difference between two measurements was always an
integer number, so for intervals < 1, you would always get 0 and for any
other non-integer interval you would get skewed results.
=> fix(net): Float interval for network speed

include/components/config.hpp
Makes error messages less confusing if for some reason a key in an
non-existent section is requested.
=> refactor(config): Throw missing section error

contrib/polybar-git.aur/PKGBUILD, contrib/polybar.aur/PKGBUILD
This is already the default but our packaging guidelines recommend this,
so we should also follow them.
=> aur: Use Release mode in cmake

.gitignore, common/release-archive.sh, doc/dev/release-workflow.rst, doc/index.rst
This new release workflow based on [OneFlow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) fixes the issue that patch releases don't live on master but only on the long-lived release branch for that minor release (e.g. 3.4).
This caused issues where executables compiled from master had a version like `3.4.0-116-gbb15e33a` even though version 3.4.3 was already released, leading people to think that the version on master was outdated.
Also, cherry-picking bug fixes onto minor release branch isn't really good practice.
With this new workflow we should have more frequent patch releases. We will need to see how long it takes from bugfix PR to finished patch release to determine whether creating a release for each bugfix is feasible and what parts we would need to …
=> Release Workflow

include/components/config_parser.hpp, include/utils/file.hpp, src/components/config_parser.cpp, src/utils/file.cpp
If a config file is a directory, ifstream would just read it as an empty
file without any errors.
Failing early here is a good idea.
=> config: Better error messages when opening files

include/adapters/net.hpp, include/modules/network.hpp, src/adapters/net.cpp, src/modules/network.cpp
I feel like having `B/s` at the end of the speed value is generally not necessary and takes too much space.
This pull request adds a `udspeed-unit` variable to be able to display the unit text in other formats. By default the value is `B/s` to keep the old behaviour. The K/M/G suffixes are still hardcoded and are displayed just before the unit.
Note: this is a "text-only" feature, setting `speed-unit = "b/s` won't change the output value from bytes per second to bits per second.
Examples:
`speed-unit = ""` will display speeds like: `128 ` `42K` `64G`
`speed-unit = "Bytes/sec"` will display speeds like: `128 Bytes/sec` `42KBytes/sec` `64GBytes/sec`
=> module::network: Ability to change speed unit text (B/s)

src/modules/script.cpp
[Module:-script](https://github.com/polybar/polybar/wiki/Module:-script#basic-settings) states that with `tail = true` interval value defaults to 0.
I was wondering why my module wasn't working as expected to realize that this condition is not taken into account.
This proposed patch fixes it.
=> Respect interval default for tail = true

include/utils/color.hpp, src/components/bar.cpp, src/components/builder.cpp, src/utils/color.cpp, tests/unit_tests/utils/color.cpp, version.txt
After almost 1.5 years, the next minor polybar release :fireworks:
I will write up a release blog post in the next few days and then we can merge this.
The drafted GitHub release can be found [here](https://github.com/polybar/polybar/releases/tag/untagged-2c9ce51665cc0c122bde) (visible to polybar team only).
Post release-checklist:
Breaking Changes:
* The new config parser imposes some restrictions on which characters can be
used in section and key names. Users shouldn't be affected by this unless they
use one of the following characters in any section or key name: `"'=;#[](){}:.$\%`
Please consult [`man 5 polybar`](https://polybar.readthedocs.io/en/latest/man/polybar.5.html) for a full reference of the new config rules.
* `internal/temperature`: The first and last ramp element are now …
=> Release 3.5.0

.travis.yml
Travis generates a bit of spam in IRC when making releases, because each branch
created will trigger a message.
=> travis: Disable notifications for passed builds

src/modules/menu.cpp
'level' is a string, not an integer
This targets the hotfix branch for 3.5.1. Since this isn't really an critical bug, I think we can leave the hotfix branch for a bit and see if there are other bugs in 3.5.0 that need fixing.
=> fix(menu): Wrong printf token in error message

include/modules/meta/base.inl
This fixes building polybar with clang++ 3.4.2.
An exemplar linking error, which we couldn't debug was this:
```text
libpoly.a(alsa.cpp.o): In function `polybar::modules::module<polybar::modules::alsa_module>::type() const':
/root/.ccache/tmp/alsa.stdout.host.4433.8kXOHg.ii:(.text._ZNK7polybar7modules6moduleINS0_11alsa_moduleEE4typeEv[_ZNK7polybar7modules6moduleINS0_11alsa_moduleEE4typeEv]+0xa): undefined reference to `polybar::modules::alsa_module::TYPE'
```
repeated for every compiled module.
=> Fix linking when built with clang++ 3.4

src/components/config.cpp
Pre 3.5.0, any key starting with 'inherit' was treated as an inherit
directive. This allowed for multiple inheritance even though it was
never inteded in that way.
3.5.0 removed that bug/feature by doing a strict check against 'inherit'
It seems people were relying on this behavior, so we are adding it back.
However multiple inheritance with multiple keys is also deprecated in
favor of the `inherit` key now supporting multiple space separated
sections.
This is because the config doesn't have a key order, but inheritance
does depend on the order the different section keys are copied over (if
multiple inherited sections define the same key).
Fixes #2269
Once this is released, we need to extend the ['Inheritance'](https://github.com/polybar/polybar/wiki/Configuration#inheritance) section …
=> fix(config): Reintroduce multiple inheritance

include/modules/meta/timer_module.hpp, src/modules/counter.cpp, src/modules/cpu.cpp, src/modules/date.cpp, src/modules/fs.cpp, src/modules/github.cpp, src/modules/memory.cpp, src/modules/network.cpp, src/modules/temperature.cpp
Since 3.5.0, we use m_interval for a modulo operation, this crashes the
bar if the interval is 0. A non-positive interval shouldn't be allowed
anyway, so we now throw an exception in that case.
Fixes #2273
=> fix(timer_module): Ensure that interval > 0

include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
If two WM events arrive withing 25ms of one-another, the second one does
not trigger a bar update.
The module state is still correct, it is just not reflected in the bar.
This somehow caused updates being swallowed in fluxbox, but only after
PR #882 was merged, even though that 25ms restriction existed long
before that.
Fixes #2272
Ref #882
=> fix(xworkspaces): Never swallow updates

src/modules/meta/base.cpp
This was a backwards-incompatible change introduced in #2199, however it
was caused because `module_formatter.has` throws an exception when the
format doesn't exist instead of just returning false.
Fixes #2262
Ref #2199
=> fix(battery): Crash when `format-low` not defined

include/utils/process.hpp
After upgrading from 3.4.3 to 3.5.0 I get this while building:
```text
In file included from /usr/src/polybar-3.5.0/src/utils/process.cpp:1:
/usr/src/polybar-3.5.0/include/utils/process.hpp:8:26: error: unknown type name 'pid_t'
bool in_parent_process(pid_t pid);
^
/usr/src/polybar-3.5.0/include/utils/process.hpp:9:26: error: unknown type name 'pid_t'
bool in_forked_process(pid_t pid);
^
/usr/src/polybar-3.5.0/include/utils/process.hpp:13:3: error: unknown type name 'pid_t'
pid_t fork_detached(std::function<void()> const& lambda);
^
/usr/src/polybar-3.5.0/include/utils/process.hpp:18:3: error: unknown type name 'pid_t'
pid_t wait_for_completion(pid_t process_id, int* status_addr = nullptr, int waitflags = 0);
^
/usr/src/polybar-3.5.0/include/utils/process.hpp:18:29: error: unknown type …
```
=> Add missing header

include/adapters/pulseaudio.hpp
A follow-up to #2270. Likely a bug in clang.
The build error it fixes is:
```text
/usr/src/polybar-3.5.0/src/adapters/pulseaudio.cpp:60:10: error: no matching function for call to 'pa_context_get_sink_info_by_name'
--
  | op = pa_context_get_sink_info_by_name(m_context, DEFAULT_SINK, sink_info_callback, this);
  | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | /usr/include/pulse/introspect.h:268:15: note: candidate function not viable: no known conversion from 'const std::initializer_list<const char *>' to 'const char *' for 2nd argument
  | pa_operation* pa_context_get_sink_info_by_name(pa_context *c, const char *name, pa_sink_info_cb_t cb, void *userdata);
  | ^
  | /usr/src/polybar-3.5.0/src/adapters/pulseaudio.cpp:134:13: error: no matching function for call to …
```
=> Fix build with clang++ 3.4

include/utils/process.hpp, src/utils/command.cpp, src/utils/process.cpp, tests/unit_tests/utils/process.cpp
Since the forked processes are still our children, we need to wait on
them, otherwise they become zombie processes.
We now fork twice, let the first fork immediately return and wait on it.
This reparents the second fork, which runs the actual code, to the init
process which then collects it.
Ref #770
=> fix(process): fork_detached created zombie processes

include/modules/meta/base.hpp, include/modules/meta/base.inl
The change in #2270 accidentally broke how we access module types.
module<Impl>::TYPE always points to the module superclass and it thus
accesses its empty TYPE field.
This mainly broke legacy action handling.
@vaygr Can you check if this still works in clang 3.4.2?
Ref #2270
=> fix: Module type always empty string

include/cairo/context.hpp, include/components/types.hpp, src/components/bar.cpp
A new set of configuration options are added to allow to set corner radii
separately. For motivation see #2294.
Additionally to the already present `radius` and `radius-{bottom,top}`
`radius-{bottom,top}-{left,right}` configuration options are added. If not
present they fall back to `radius-bottom`, `radius-top` or ultimately `radius`
to preserve current semantics.
This implements #2294.
See provided patch below (to be applied to Home → Configuration).
```patch
--- configuration_old.md	2020-12-13 16:33:34.677959229 +0100
+++ configuration_new.md	2020-12-13 16:38:17.929004974 +0100
@@ -201,8 +201,10 @@
; Note: This shouldn't be used together with border-size because the border 
; doesn't get rounded. For this to work you may also need to enable 
; pseudo-transparency or use a compositor …
```
=> feat(conf) Properties for {bottom,top}-{left,right} radius

.github/workflows/release.yml, CHANGELOG.md, CONTRIBUTING.md, doc/dev/release-workflow.rst
Right now we manually create a changelog for each release, this is quite time
consuming for larger releases because we need to go through all the commits for
that release.
With this contributors should add their changes to the changelog directly with
the PR and for a release, we can basically copy-paste the changelog with some
minor cleanup.
This has the added benefit of precise documentation for which features and bugs
have been addresses but not yet released.
This follows the format and philosophy of [keep a
changelog](https://keepachangelog.com/en/1.0.0/).
=> Adopt "keep a changelog"

doc/conf.py
Searching up from the conf.py only works if it is inside the repository
and not for out-of-tree builds (because conf.py gets configured in the
build directory).
This is a follow-up to #2311
=> fix(docs): Support out-of-tree builds

src/components/config.cpp
An empty color value in the config should be treated as if no color was
specified (explicitly). This is the same behavior as before.
=> fix(config): Don't treat an empty value as invalid

CHANGELOG.md, include/x11/extensions/xkb.hpp, src/modules/xkeyboard.cpp, src/x11/extensions/xkb.cpp
Closes #316
Adds `%variant%` variable to `label-layout` option in the xkeyboard module. As
suggested, I took the group name and grabbed the string inside the parens.
=> feat(xkeyboard): Add variant support to layout label

CHANGELOG.md, doc/conf.py, src/components/config.cpp, version.txt
Post-release checklist:
- Don't use `git` when building documentation ([`#2311`](https://github.com/polybar/polybar/issues/2309))
- Empty color values are no longer treated as invalid and no longer produce an error.
Includes changes from #2311, #2312, and #2315
Draft Release: https://github.com/polybar/polybar/releases/tag/untagged-1feb0647c0889d90abb1
=> Release 3.5.3

.github/workflows/ci.yml, doc/dev/release-workflow.rst
The `code-blocks::` directive requires a language before sphinx 2.0. This caused a warning (but not an error) in CI and readthedocs, causing that code block to be stripped out.
=> Fix sphinx warnings

CHANGELOG.md, src/components/controller.cpp
The intention was to remove tags that won't have an effect and join
together consecutive tags.
However the patterns used can just as well appear in regular text, so
this can replace characters inside user defined text and not just
formatting tags.
Fixes #2331
=> Remove tag compaction "optimizations"

CHANGELOG.md, config/config.cmake, include/components/controller.hpp, include/modules/meta/base.hpp, include/modules/meta/base.inl, include/modules/unsupported.hpp, src/components/controller.cpp
Creates new IPC commands to toggle the visibility of a specific module. End goal (as expressed in #2108) is to stop processing hidden modules, although I will probably complete an initial implementation to just hide the modules.
```sh
$ polybar-msg [-p PID] cmd hide.mymodule # Hides module mymodule
$ polybar-msg [-p PID] cmd show.mymodule # Shows module mymodule
$ polybar-msg [-p PID] cmd toggle.mymodule # Toggles visibility of mymodule
```
Closes #2108
=> feat: Module Visibility

CHANGELOG.md, include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
This is a continuation of @Lomadriel's work in #1693. There were some edge cases that the PR didn't handle.
Now the urgent hint should always reflect the state in the window manager. It is a bit more resource intensive because it has to go through all the windows to update the urgent hint.
Fixes #1081 
Closes #1693 
We can remove the note about the urgency hint from the xworkspaces page
=> feat(xworkspaces): Persistent urgent hint

CHANGELOG.md, config/config.cmake, include/modules/meta/base.inl
Adds an option to initially hide a module. I'm separating this from an upcoming
refactor of the visibility system to use the new action router to get this merged quicker.
```dosini
; Defaults to false
hidden = true
```
Continuation of #2320
=> Add config option for visiblity (#2320 cont'd)

CHANGELOG.md, include/adapters/net.hpp, src/adapters/net.cpp, src/modules/network.cpp
Allows you to specify `interface-type=wired/wireless` instead of `interface=ifname`
Closes #339
=> feat(net): interface discovery

CHANGELOG.md, include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
In the **xworkspace** module, added %nwin% token to display the number of windows in a workspace. Affects the `label-active`, `label-occupied`, `label-urgent` and `label-empty` properties.
Closes #604 
At the **Modules: xworkspace** page, add the %nwin% as an available token for `label-active`, `label-occupied`, `label-urgent` and `label-empty` properties
=> Add support for %nwin% in xworkspaces label

include/modules/alsa.hpp, include/modules/backlight.hpp, include/modules/bspwm.hpp, include/modules/date.hpp, include/modules/i3.hpp, include/modules/menu.hpp, include/modules/meta/base.hpp, include/modules/meta/base.inl, include/modules/mpd.hpp, include/modules/pulseaudio.hpp, include/modules/systray.hpp, include/modules/xbacklight.hpp, include/modules/xkeyboard.hpp, include/modules/xworkspaces.hpp, include/utils/action_router.hpp, src/components/controller.cpp, src/modules/alsa.cpp, src/modules/backlight.cpp, src/modules/bspwm.cpp, src/modules/date.cpp, src/modules/i3.cpp, src/modules/menu.cpp, src/modules/mpd.cpp, src/modules/pulseaudio.cpp, src/modules/systray.cpp, src/modules/xbacklight.cpp, src/modules/xkeyboard.cpp, src/modules/xworkspaces.cpp, tests/CMakeLists.txt, tests/unit_tests/utils/action_router.cpp
Action implementation inside module becomes much cleaner because each
module just registers action names together with a callback (pointer to
member function) and the action router does the rest.
The implementation is neat because we can just port over modules one-by-one because the input method kept the exact same semantics. Modules just need to stop overwriting the `input` function and start registering their actions to use the new system.
This would make it much easier to implement universal module actions like in #2320
=> module: Implement action router

.github/workflows/ci.yml, cmake/cxx.cmake, include/components/bar.hpp, include/components/controller.hpp, include/components/renderer.hpp, include/components/screen.hpp, include/events/signal_receiver.hpp, include/modules/battery.hpp, include/modules/bspwm.hpp, include/modules/i3.hpp, include/modules/ipc.hpp, include/modules/meta/base.hpp, include/modules/meta/event_module.hpp, include/modules/meta/inotify_module.hpp, include/modules/meta/static_module.hpp, include/modules/meta/timer_module.hpp, include/modules/script.hpp, include/modules/unsupported.hpp, include/modules/xbacklight.hpp, include/modules/xkeyboard.hpp, include/modules/xwindow.hpp, include/modules/xworkspaces.hpp, include/tags/parser.hpp, include/utils/file.hpp, include/x11/background_manager.hpp, include/x11/connection.hpp, include/x11/tray_manager.hpp, tests/unit_tests/components/command_line.cpp
When implementing the action router (#2336), I mistakenly created a `stop` function in the mpd module for the stop action. This completely broke the module and the bar and was quite difficult to debug.
With this compiler warning, this error would have been caught earlier.
=> Add compiler warning for missing override specifier

include/components/config_parser.hpp, tests/unit_tests/components/config_parser.cpp
Because we passed a temporary as the logger, it gets destroyed after the
config_parser constructor returns and when the logger is called in
config_parser it operates on a dangling reference.
Ref: https://stackoverflow.com/q/35770357/5363071
=> fix(config_parser): UB in logger

CHANGELOG.md, doc/man/polybar.5.rst, include/components/config_parser.hpp, src/components/config_parser.cpp, tests/unit_tests/components/config_parser.cpp
* Introduce an escape character '\\'.
* Warn users about unescaped characters (only backslashes for now).
* For now, treat a single unescaped backslash as a literal backslash character.
* Treat two consecutive backslashes as a single literal backslash character.
Implements first step of #2354
See #2354
=> Add initial support for an escape character #2354

CHANGELOG.md, include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
Added reverse-scroll option for xworkspaces module. The default is to set it to false, that way users do not have to change their configuration files if they want old behavior.
None
The new setting should be documented in the xworkspaces section, probably under basic settings.
=> add reverse-scroll option for xworkspaces module

include/components/bar.hpp, include/components/renderer.hpp, include/components/renderer_interface.hpp, include/components/types.hpp, include/events/signal.hpp, include/events/signal_fwd.hpp, include/tags/action_context.hpp, include/tags/context.hpp, include/tags/dispatch.hpp, src/CMakeLists.txt, src/components/bar.cpp, src/components/ipc.cpp, src/components/renderer.cpp, src/tags/action_context.cpp, src/tags/context.cpp, src/tags/dispatch.cpp, tests/CMakeLists.txt, tests/unit_tests/tags/action_context.cpp, tests/unit_tests/tags/dispatch.cpp
This is a first proof of concept for #2344
Right now only the current colors, font and attribute activations are stored.
But the plan is to also keep track of all action areas and alignment so that the
renderer is completely independent from the actual formatting tags.
Closes #2344
Maybe we want to write a page about the architecture.
=> renderer: Keep Formatting State in separate component

CHANGELOG.md, include/modules/i3.hpp, include/utils/i3.hpp, src/modules/i3.cpp, src/utils/i3.cpp
Given `pin-workspaces = true`, setting `show-urgent = true` will show urgent workspaces on the current bar even when the workspace is not associated with the current monitor. If `pin-workspaces = false`, this option has no effect.
Closes #2374 
```patch
--- wiki.old	2021-02-14 05:34:34.898430279 +0100
+++ wiki.new	2021-02-14 05:37:25.829103300 +0100
@@ -34,6 +34,16 @@
; Default: false
pin-workspaces = true
+; Show workspaces having the urgent hint set in the bar
+; regardless of the workspace being on the current output
+; or not.
+;
+; This option only makes sense in when pin-workspaces is
+; enabled.
+;
+; Default: false
+show-urgent = true
+
; This will split the workspace name on ':'
; Default: false
strip-wsnumbers = true
```
=> feat(conf) always show urgent workspaces in i3

CHANGELOG.md, include/modules/backlight.hpp, src/modules/backlight.cpp
Adds a `use-actual-brightness` option to `internal/backlight`, which specifies whether to use the `actual_brightness` file in `/sys/class/backlight/%card%/` or the `brightness` file. Defaults to true **unless** the card is an amdgpu card.
Fixes/closes #2367
https://github.com/polybar/polybar/wiki/Module:-backlight - needs the `use-actual-brightness` option documented.
=> internal/backlight - add use-actual-brightness option

CHANGELOG.md, include/cairo/context.hpp, include/cairo/types.hpp, src/components/renderer.cpp
This PR exists to change the behaviour when applying a `radius` together with `border-size` with a minimal amount of code changes. Polybar is now able to display a round border (also supporting the functionality added in https://github.com/polybar/polybar/pull/2297) :tada: 
In order to avoid bigger changes, I've implemented it so that the rounded border gets its size and color from the top border configuration (`border-size` / `border-top-size` and `border-color` / `border-top-color` respectively). 
While I am not sure how to implement the configuration in a more user-friendly way without changing the current configuration options, I would be glad to add any changes you suggest.
While the idea to implement this came up whilst styling my system, this issue is a good representation: …
=> feat: Rounded bar border

cmake/common/utils.cmake, cmake/libpoly.cmake, cmake/modules/FindALSA.cmake, cmake/modules/FindCURL.cmake, include/utils/color.hpp, src/CMakeLists.txt, src/utils/color.cpp, tests/unit_tests/utils/color.cpp
In #2387, it was reported that configuration doesn't work in cmake 3.10. While fixing that, I stumbled upon some other build issues. This should fix all of them.
Our cmake code relied on functionality from cmake up to version 3.12 and compilation failed with gcc5.
Older cmake versions also did not provide module files for alsa and curl that created targets and because of that we didn't link them.
Fixes #2387
Fixes #2393
=> Fix compilation on older versions

include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
While it shouldn't happen with compliant WMs, it was possibe to crash
polybar with _NET_CURRENT_DESKTOP >= _NET_NUMBER_OF_DESKTOPS and this
should not be possible.
Includes polybar/xpp#31
Fixes #2398
=> fix(xworkspaces): Segfault for wrong _NET_CURRENT_DESKTOP

CHANGELOG.md, include/utils/math.hpp, tests/unit_tests/utils/math.cpp
For example if lower / upper = 0.019 (1.9%), it would return 1% instead of 2%
Fixes #2399
=> fix: unbounded_percentage always rounded down

include/cairo/context.hpp, include/cairo/types.hpp, src/components/renderer.cpp
With the merging of PR #2359, borders on curved corners were created by placing a rectangle with a curved corner behind the main polybar. However, when the main polybar is transparent, you can see the rectangle behind the main bar. This, instead, turns the rectangle into a curved line and only draws it on the border so that there is no rectangle behind the main bar to show when the bar is transparent.
Fixes #2406
=> Fix issues with border corner radii

CHANGELOG.md, config/config.cmake, src/components/bar.cpp
Previously wm-restack only supported bspwm and i3. Both have a special
top-level window that polybar detects and places itself directly above.
This patch adds wm-restack=generic which simply lowers polybar to the
very bottom of the stack. This option was tested and confirmed to work
with xmonad which doesn't have a special top-level window and therefore
doesn't require special handling like bspwm and i3.
Fixes #2205
Closes #1657 
I suggest the following changes to the configuration page on the wiki:
```
; Restack the bar window. Fixes the issue where the
; bar is being drawn on top of fullscreen windows.
;
; Currently supported options:
;   generic (works in xmonad, may work with other WMs)
;   bspwm
;   i3 (requires: `override-redirect = true`)
; wm-restack =
```
=> Add wm-restack=generic option that lowers polybar to the bottom of the stack

CHANGELOG.md, doc/conf.py
Before sphinx 4.0, this was the default but was changed in 4.0.
Now by default the folder structure looks like this:
```
man
├── 1
│   └── polybar.1
└── 5
└── polybar.5
```
This restores the old behavior where there weren't individual folders
for the different sections:
```
man
├── polybar.1
└── polybar.5
```
Fixes #2424
Ref: https://www.sphinx-doc.org/en/master/changes.html#id14
=> fix(build): Disable sphinx manpage section dirs

CHANGELOG.md, include/modules/bspwm.hpp, src/modules/bspwm.cpp
New config option 'occupied-scroll' for bspwm module that allows scrolling only occupied desktops.
Closes #2427
Update bspwm module wiki page
=> [module/bspwm] Option to scroll through occupied desktops only

CHANGELOG.md, src/x11/tray_client.cpp, src/x11/tray_manager.cpp
XCB_BACK_PIXMAP_PARENT_RELATIVE requires that the client has the same
depth as the tray window.
There was an issue with dropbox having a depth of 32 and the tray window
having a depth of 24 that caused the configuration of the icon to fail.
It would then be displayed outside of the bar because the catch block
was not hit (different exception).
We now just don't configure XCB_CW_BACK_PIXMAP. This seems to work and
is also what stalonetray does.
This does not fix the issue with dropbox having an arbitrary background.
I also noticed that these are the same symptoms as #1679, so I think that should be fixed now as well (though I can't confirm because the issue no longer occurs because of a new synology drive version)
Fixes #2430
Fixes #1679
=> fix(tray): Support clients with different depths

CHANGELOG.md, src/modules/bspwm.cpp
T@ is producing an warning message in bspwm. Since T@ is not a special state in bspwm I've added a case so that it can be ignored. 
Fixes #2371
=> Adding case to ignore T@ in bspwm

CHANGELOG.md, doc/user/actions.rst, include/components/controller.hpp, include/modules/meta/base.hpp, include/modules/meta/base.inl, include/modules/unsupported.hpp, src/components/controller.cpp
Adds universal module visibility control actions `toggle_visible`, `set_visible`, and `set_invisible`.
#2108
#2320
#2342
=> Universal Visibility Action (#2320 cont'd)

src/modules/fs.cpp
Empty formats in the fs module would still add spacing, resulting in large extra spacing before, after, or inside the module if some mountpoints weren't shown for some reason.
Fixes #2458
=> fix(fs): Only add spacing between shown mountpoints

CHANGELOG.md, doc/user/actions.rst, include/modules/ipc.hpp, src/modules/ipc.cpp
Instead of just allowing hook numbers to be executed, the user can
send arbitrary text and the IPC module will put it in the bar. The IPC
payload format is extended to accept an arbitrary string if the first
character after the module name is ':'.
polybar-msg hook test :'%{F#4444ff}hello%{F-}'
I did not make a new module as requested by @patrick96 as the modifications to the IPC module are minimal and the actions are reused as is. Tell me what you think.
Fix #2455
=> feat(ipc): allow receiving arbitrary text on IPC socket

CHANGELOG.md, src/main.cpp, src/x11/extensions/randr.cpp
Previously, when splitting an output into two monitors, `polybar -m`
would report both the splitted monitors and the output. This was not
caught by the the clone detection as the detection works by removing
monitors contained into another monitors (and monitors were excluded
from that logic) and we want the other way around: outputs covered by
monitors should be ignored.
Instead of trying to detect covered outputs, the solution is quite
simple: when monitors are supported, do not consider outputs. A
monitor can be set primary (and RandR reports primary outputs as
primary monitors). The only information we would miss from monitors
are things like refresh rate and EDID. We don't need that, so we are
fine.
As monitors are only created for connected output (and they are in
this case "active") …
=> fix(monitor): do not include outputs when monitors are supported

CHANGELOG.md, include/utils/string.hpp, src/modules/memory.cpp, src/utils/string.cpp
Memory/swap values can now be displayed in MiB instead of GiB when the value is less than 1 GiB, for better precision.
For example, display 512 MiB instead of 0.50 GiB.
The following tokens have been added to the memory module in order to activate this behavior from config:
```
;   %used%
;   %free%
;   %total%
;   %swap_total%
;   %swap_free%
;   %swap_used%
```
Closes #2472 
The documentation of the memory module should be updated with the tokens described earlier, and a description on their behavior.
=> [module/memory] Display MiB instead of GiB when GiB value is less than 1GiB

CHANGELOG.md, src/modules/xworkspaces.cpp
The scroll handler had two issues:
* It did not respect the order the desktops where displayed in
* It would not wrap around on the first desktop because of an integer
underflow
Fixes #2491
=> fix(xworkspaces): Fix scrolling

include/modules/ipc.hpp, include/modules/menu.hpp, include/modules/meta/static_module.hpp, include/modules/xbacklight.hpp, include/modules/xworkspaces.hpp, src/modules/ipc.cpp, src/modules/xwindow.cpp, src/modules/xworkspaces.cpp
The static modules don't need any threads because nothing actually runs in them.
The ipc module also isn't really a static module since the hook commands should run in a thread (though it does not do so yet)
=> Remove threads from static modules

include/modules/meta/base.hpp, include/modules/meta/base.inl, include/utils/action_router.hpp, src/CMakeLists.txt, src/modules/alsa.cpp, src/modules/backlight.cpp, src/modules/bspwm.cpp, src/modules/date.cpp, src/modules/i3.cpp, src/modules/ipc.cpp, src/modules/menu.cpp, src/modules/mpd.cpp, src/modules/pulseaudio.cpp, src/modules/systray.cpp, src/modules/xbacklight.cpp, src/modules/xkeyboard.cpp, src/modules/xworkspaces.cpp, src/utils/action_router.cpp, tests/unit_tests/utils/action_router.cpp
The previous CAST_MOD(Impl) for the action_router constructor was
illegal because `this` is not yet of type Impl (because the subclass
constructor has not run yet).
The action_router now accepts std::function for its callbacks.
Fixes #2519
=> fix(modules): Avoid downcast in module constructor

include/modules/meta/base.hpp, include/modules/meta/base.inl, include/modules/unsupported.hpp, src/components/controller.cpp
Addresses point 2 of #1732.
Since the joins are in the `stop` method, the vtable is no longer acceded during the destruction. This also solve the CRTP problem.
=> fix(modules): move join in a new method

include/components/config_parser.hpp, src/components/config_parser.cpp, tests/unit_tests/components/config_parser.cpp
This PR adds an additional context with configuration file name and line number to some error messages in the `config_parser`, which helps the user to find configuration errors easier.
It also a bit optimizes exceptions handling, since we don't need to re-throw an exception in the `parse_file` function.
To test it, you could use this minimal configuration file with an error:
```
[bar/example]
modules-center = date
[module/date]
type = internal/date
interval = 5
; Error: non-escaped backslash
date =\
label = %date%
```
And run it by this way: `./bin/polybar -c config_demo -s example`
Expected output (error message now contains file name and line number):
```
notice: Parsing config file: config_demo
error: config_demo:9: Value '\' of key 'date' contains one or more unescaped backslashes, …
```
=> config_parser: Improve error messages

include/modules/ipc.hpp, src/modules/ipc.cpp
Seems that when the execution of the initial hook is in the start function, polybar can get stuck.
I also refactored how we store the initial hook.
Fixes #2477
=> ipc: Move running initial hook to update function

CHANGELOG.md, src/modules/ipc.cpp
Current behavior makes it so that empty ipc module outputs get formatted. This means, when the output string is empty, there will be (depending on the module margins) extraneous spaces in the bar at the position of the ipc module.
This PR makes ipc modules have the same behavior as script modules when dealing with empty output strings. That is, when the output of the ipc module is empty, no formatting gets applied so that adjacent modules become neighbors (i.e. no margins or separators get applied to the empty string).
I found this bug while making an update module that changes output on click actions and on an interval, as mentioned [here](https://github.com/polybar/polybar/issues/786#issuecomment-679112469). Preventing the module from appearing in the bar when there are no updates …
=> fix(ipc): don't format empty strings

tests/CMakeLists.txt.in
I followed the instructions on
https://github.com/polybar/polybar/wiki/Testing, and this happened to
me:
$ cmake .. -DBUILD_TESTS=ON
...
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
fatal: invalid reference: master
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:40 (message):
Failed to checkout tag: 'master'
make[2]: *** [CMakeFiles/googletest.dir/build.make:99: googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
CMake Error at tests/CMakeLists.txt:19 (message):
Build step for googletest failed: 2
It looks like the problem is that …
=> Make it possible to run tests.

CHANGELOG.md, include/x11/tray_manager.hpp, src/x11/tray_manager.cpp
This adds a new `tray-foreground` config option, and uses it instead of
the `tray-background` setting to build up the `_NET_SYSTEM_TRAY_COLORS`
property. I'm pretty sure that the previous behavior was a mistake (this
was introduced in 94298741b6de08e79131006504850820bdff9024 which is a
pretty large diff).  For me and some other people, this results in a
black icon being drawn on top of a black background, which is pretty
useless! I would say that this diff fixes
https://github.com/polybar/polybar/issues/2235. Note: the old code dealt
with `unsigned int` and maxed values out at 0xff. The new code deals
with `uint16_t` and maxes values out at 0xffff. I haven't found the
relevant documentation to justify this change, but from manually
testing, I'm pretty confident this is the right change. …
=> Add support for a `tray-foreground` setting.

CHANGELOG.md, include/adapters/mpd.hpp, include/adapters/net.hpp, include/modules/battery.hpp, include/modules/meta/timer_module.hpp, include/modules/mpd.hpp, src/adapters/mpd.cpp, src/adapters/net.cpp, src/modules/battery.cpp, src/modules/mpd.cpp
Where used for timing, replace system_clock with steady_clock so that the updating of modules isn't affected by system clock changes.
The m_updated_at field of the mpd module was removed instead of having
its clock changed because it became unused in commit 645a3142a19747c252d24cc71414d40a8eb5f7dc.
This fixes #857 and #1932. Also replaces PR #1725, since we don't need
our own implementation of condition_variable anymore since people who
update their polybar should have GCC 10 by now (which was released in may 2020).
Fixes #857
Fixes #1932
Closes #1725
=> Replace system_clock with steady_clock

CHANGELOG.md, src/modules/battery.cpp
Get battery status before check if adapter is online. Avoid to have label-charging when the ac is plugged in but the battery do not charge.
[`#2363`](https://github.com/polybar/polybar/issues/2363)
Fixes #2563
=> Get battery status before adapter. (#2363)

src/adapters/net.cpp
This PR is a follow up change to #2025 attempt to improve the adapter/net.cpp:find_interface()
to return a interface name that is currently running if any interface is found, else just return the 
first one found.
This will allow the interface-type to work with multiple net interface
of the same type, and prefer to one that is currently connect to
a network. This works great HW with multiple Ethernet port and user
expect to occasionally swap between the two.
=> feat(net): improve interface discovery 

CHANGELOG.md, include/cairo/font.hpp, include/components/bar.hpp, include/components/controller.hpp, include/components/eventloop.hpp, include/events/signal.hpp, include/ipc/ipc.hpp, include/modules/meta/base.hpp, include/utils/command.hpp, include/utils/scope.hpp, src/components/bar.cpp, src/components/controller.cpp, src/components/eventloop.cpp, src/ipc/ipc.cpp, src/main.cpp, src/polybar-msg.cpp, src/utils/command.cpp
Some eventloop related cleanups i think are necessary. May also uncover some object lifetime issues.
=> Eventloop cleanup

src/ipc/util.cpp, src/main.cpp
If two processes call `mkdir` at the same time, the second one will fail
and wrongly assume the folder wasn't created properly.
We now first check if the folder really doesn't exist and we also catch
any IPC initialization errors and disable IPC instead of crashing the
whole bar.
=> Fix race condition when creating socket folder

doc/conf.py
Defer parsing the version read from version.txt until it's about
to be used, in order to fix an obscure bug involving indirect
pkg_resources.
When pkg_resources are imported, they override packaging with their own
pkg_resources.extern.packaging.  Depending on the system, this could
either wrap the vendored pkg_resources._vendor.packaging or system
packaging.  For some reason, in the latter case the Version objects
created prior to the wrapping are incompatible with the objects created
afterwards.  This causes the doc build to fail with:
```
Exception occurred:
File "/tmp/polybar/build/doc/conf.py", line 249, in run
if directive_version > version_txt:
TypeError: '>' not supported between instances of 'Version' and 'Version'
```
This happens because apparently pkg_resources are imported …
=> doc: Defer parsing version_txt to fix an obscure bug

CHANGELOG.md, include/adapters/net.hpp, src/adapters/net.cpp, src/modules/network.cpp
Adds netspeed parameter which is basically sum of up and down speeds
Fixes #1083, Although this doesn't add dynamic icons of up and down
`netspeed` parameter uses needs to be described in the network module documentation.
=> Add netspeed parameter (#1083)

CHANGELOG.md, include/x11/icccm.hpp, src/components/bar.cpp, src/x11/icccm.cpp
When polybar is remapped (either through IPC or something like xdo
show), openbox positions it somewhere on the screen using the same
positioning algorithm as it would for regular windows.
If the position and size is set in the WM_SIZE_HINTS atom, openbox will
respect the position and size declared by the window.
Fixes #2021
=> fix: Set WM_SIZE_HINTS to fix position in openbox

CHANGELOG.md, include/adapters/script_runner.hpp, include/modules/script.hpp, src/adapters/script_runner.cpp, src/modules/script.cpp
_The behavior is not changed unless the feature is used. Old configuration files should work the same way._
This PR adds formatting for script failure (when exited with non-zero exit status):
```ini
format-fail = <label-fail>
; and all the others format-fail-*
label-fail = %output%
; and all the others label-fail-*
```
Falls back to `format`, if `format-fail` isn't specified.
The feature is disabled for `tail=true` scripts, since they either run indefinitely (so exit status doesn't have a change to be used) or stop for an `interval` that should be relatively short compared to the lifetime of a script. In both scenarios, exit status is received too late for it to be useful so there's no way to implement meaningful formatting for those scripts.
Closes #2588 
The following should be added to …
=> feat(script): add formatting for script failure

CHANGELOG.md, doc/CMakeLists.txt
Skip manpage and html doc installation if they weren't generated
Otherwise we get errors like this:
CMake Error at doc/cmake_install.cmake:46 (file):
file INSTALL cannot find
"/<<PKGBUILDDIR>>/build/doc/html": No such file or
directory.
Call Stack (most recent call first):
cmake_install.cmake:59 (include)
I noticed this issue when packaging the latest release on Debian (I should consider building and shipping the html docs BTW).
No issue reported AFAIK.
=> Skip manpage and html doc installation if they weren't generated

CHANGELOG.md, cmake/cxx.cmake
CMAKE_EXE_LINKER_FLAGS contains, among other things, the LDFLAGS which
many distros use to universally apply linker flags.
When completely replacing CMAKE_EXE_LINKER_FLAGS, these flags are lost.
=> fix(build): Do not replace CMAKE_EXE_LINKER_FLAGS

CHANGELOG.md, include/utils/units.hpp, src/components/bar.cpp, src/utils/units.cpp, tests/unit_tests/utils/units.cpp
Regression from #2578 where `tray-offset-x`, `tray-offset-y`, `offset-x`, and `offset-y` mistakenly where capped below at 0
=> fix: Allow negative values for tray and bar offset

CHANGELOG.md, src/polybar-msg.cpp
As stated in the 3.6.0 changelog, 
> polybar-msg hook is deprecated in favor of using the hook action. polybar-msg will tell you the correct command to use.
However, it instructs to use another `polybar-msg hook` command, instead of `polybar-msg action`.
Current :
```bash
$ polybar-msg hook count-updates_ipc 1
Warning: Using IPC hook commands is deprecated, use the hook action on the ipc module: polybar-msg hook "#count-updates_ipc.hook.0"
Successfully wrote action '#count-updates_ipc.hook.0' to PID 33971
```
Fixed :
```bash
$ /usr/local/bin/polybar-msg hook count-updates_ipc 1
Warning: Using IPC hook commands is deprecated, use the hook action on the ipc module: /usr/local/bin/polybar-msg action "#count-updates_ipc.hook.0"
Successfully wrote action '#count-updates_ipc.hook.0' to PID …
```
=> Fix hint message when using deprecated `polybar-msg hook`

CHANGELOG.md, include/components/bar.hpp, src/components/bar.cpp, src/x11/icccm.cpp
Since polybar sets WM_NORMAL_HINTS, awesomeWM for some reason no longer
respect the position set by polybar before mapping.
reconfiguring the window position once again after mapping the window,
again positions it correctly.
Reported on reddit: https://www.reddit.com/r/Polybar/comments/terkd8/polybar_misplacement_in_awesome_wm/
=> fix: Positioning in awesomeWM

CHANGELOG.md, src/modules/xworkspaces.cpp
Because the X server is asynchronous, there is no guarantee that after
reading _NET_CLIENT_LIST, all windows still exist.
For that reason we need to handle XCB_WINDOW errors appropriately.
=> xworkspaces: Deal with disappearing windows

CHANGELOG.md, include/components/bar.hpp, include/components/types.hpp, include/events/signal.hpp, include/events/signal_fwd.hpp, include/x11/cursor.hpp, src/components/bar.cpp, src/components/controller.cpp, src/x11/cursor.cpp
If only cursor-click or cursor-scroll is defined, but not the other, the
bar could try to set the cursor to the empty string which resulted in an
error.
Minimal example:
```dosini
[bar/example]
modules-left = text
enable-ipc = true
; cursor-click = pointer
cursor-scroll = ns-resize
[module/text]
type = custom/text
content = %{A1:true:}Click%{A1}%{A4:true:}Scroll%{A4}
```
When mousing over `Scroll` and then over `Click`, polybar produces an error because it tries to change the cursor from `ns-resize` to the empty string (which is not valid).
=> fix mouseover error when only one cursor is defined

include/x11/ewmh.hpp, src/modules/xworkspaces.cpp, src/x11/ewmh.cpp
This way, we don't have to explicitly get the xcb_ewmh_connection_t
pointer from the object and can simply derference the ewmh instance
itself.
=> Make ewmh_connection act as xcb_ewmh_connection_t*

CHANGELOG.md, src/adapters/script_runner.cpp
**BREAKING CHANGE:** behaviour is changed for failing scripts with constant output.  
Before this PR they would "blink" due to the `clear_output` call on every other iteration (see #2636).
Closes #2636
=> fix(script): do not hide failing scripts with constant output

CHANGELOG.md, include/modules/pulseaudio.hpp, src/modules/pulseaudio.cpp
When we enable natural scrolling option in libinput, it sends scroll down even when we swipe up on the touchpad.  
This makes the pulseaudio module feel weird.  
This option fixes that.
Add the following to the wiki under Pulseaudio:
```ini
reverse-scroll = false
```
=> feat(pulseaudio): define invert-scroll option

CHANGELOG.md, include/adapters/script_runner.hpp, include/modules/script.hpp, src/adapters/script_runner.cpp, src/modules/script.cpp
This PR fixes timing inconsistencies of `script` module output, first described at #2630.  
Module now receives updates from corresponding runner callback, instead of directly calling `get_*` methods of the runner.
Synchronization had to be moved to the module itself. I don't quite like the way I did it here as it still leaves a possibility for inconsistencies to occur (e.g. if runner calls update handler during `get_output` execution).  
The alternative would be to hold lock for the whole execution of `get_output`. It heavily relies on (only) `module::get_output` calling `get_format`, since explicit locking inside `get_format` would lead to deadlock. Although this implementation would eliminate any inconsistencies, I find it unstable architecture-wise. Maybe I've missed some other …
=> fix(script): output timing inconsistencies

CHANGELOG.md, include/modules/text.hpp, src/modules/text.cpp
Makes the text module use the standard format+label as all other modules in a non-breaking way.
The `content` key is deprecated in favor of `format` which has the exact same functionality, except that it also supports the `<label>` tag.
Closes #1331
Closes #1342
Fixes #2673
The example under "Additional Formatting" in the wiki should be:
```dosini
; @deprecated Use format and/or label to define the module text
; content = Some random label
; Available tags:
;   <label> (default)
format = <label>
format-background = #000
format-foreground = #fff
format-padding = 4
; No tokens available
label = Some random label
```
=> feat(text): Add standard format with label

CHANGELOG.md, src/adapters/script_runner.cpp
Fixes the issue when output is not cleared after `exec-if` failed.
Closes #2674
=> fix(script): clear output when exec-if fails

CHANGELOG.md, include/components/renderer.hpp, src/components/renderer.cpp
Minimal example
```dosini
[bar/example]
modules-left = text
line-size = 2
width = 100
[module/text]
type = custom/text
content = Foo %{O10} Bar
content-underline = #ff0000
```
*Broken:*
*Fixed:*
=> fix: No overlines/underlines being drawn when using offsets

CHANGELOG.md, include/components/bar.hpp, src/components/bar.cpp
When a module is clicked, only wait for the double click interval if a double click action is associated with that module. Otherwise trigger the click right away.
The check is button specific, so if the user performs a _right_ click on an area that has an action for a double _left_ click, the right click is triggered immediately.
Fixes: #2663
=> fix: check if double click action associated

CHANGELOG.md, include/modules/backlight.hpp, src/modules/backlight.cpp
Adds the `scroll-interval` option to `internal/backlight`, which allows the user to set the scrolling interval when changing the backlight module.
Closes #2696
New config option should be described in Wiki.
=> Added `scroll-interval` option to `internal/backlight`

CHANGELOG.md, src/components/bar.cpp, src/x11/window.cpp
When the bar is hidden, the struts should be 0 so that WMs can resize
their windows and not leave a gap.
Ref #2701
=> fix(bar): Update struts when hiding

CHANGELOG.md, src/modules/fs.cpp
When no mountpoints are specified for an `internal/fs` module, use `/` as a fallback and display a warning.
Impelements a part of #2572 
In 'Module: filesystem', in the section 'Basic settings', the lines
```
; Mountpoints to display
mount-0 = /
mount-1 = /home
mount-2 = /var
```
should be changed to 
```
; Mountpoints to display
; Default: /
mount-0 = /
mount-1 = /home
mount-2 = /var
```
=> filesystem: Use fallback if no mountpoints are specified

CHANGELOG.md, include/adapters/pulseaudio.hpp, src/adapters/pulseaudio.cpp
If context_state_callback is called before we call
pa_threaded_mainloop_wait in the main thread, the signal is lost and we
wait forever.
Fixes #2707
Ref #2699
Ref #2697
=> fix(pulse): Hanging during connection setup

CHANGELOG.md, include/components/config.hpp, src/components/bar.cpp
This PR adds error handling for value errors when parsing deprecated config values (e.g. when `convert<double>` throws, like in #2724).
I didn't add `warn_deprecate`, since this warning would be the next thing users see after they fix the original error.
Closes #2724
=> fix: error reporting for deprecated config values

src/x11/tray_manager.cpp
Tray is no longer pushed off the bar when the bar overflows.
Details in #2689
sample config:
```
[bar/example]
modules-left = text tray
enable-ipc = true
tray-position = adaptive
width = 50%
offset-x = 50%
[module/text]
type = custom/text
content = AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
[module/tray]
type = internal/tray
```
=> tray: tray no longer pushed off the bar

include/components/bar.hpp, include/components/controller.hpp, include/x11/tray_manager.hpp, src/components/bar.cpp, src/components/controller.cpp, src/x11/tray_manager.cpp
This PR removes the `tray-position` option `adaptive` which was temporarily added in #2595.
It's part of a series of changes outlined in #2689 . Now the tray module is automatically activated when it's added as a module
Part of #2689
=> tray: removed tray-module = adaptive option.

CHANGELOG.md, include/modules/backlight.hpp, src/modules/backlight.cpp
Implements the automatic detection of cards for the backlight module(See #2572)
When no `card` is specified, the backlight module looks for a viable card  in `/sys/class/backlight/` and uses that.
Implements part of  #2572 
in modules:backlight the following lines should be changed from: 
```
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
```
to:
```
; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
; Default: first usable card in /sys/class/backlight
card = intel_backlight
```
=> backlight: auto-detect default card

src/x11/tray_manager.cpp
I decided to check for the status in the tray_manager since we have the tray_position there. This still results in unnecessary signals being sent but I couldn't find a cleaner way to do it without complicating the code by a bit. 
Fixes #2741
=> fix:  tray isn't visible when a module updates

include/components/config.hpp, include/components/controller.hpp, src/components/config.cpp, src/components/controller.cpp
I fixed this issue by creating event handlers for every include-file present in `m_included`. I also added a method `get_included_files` in the controller class to make this possible.
Fixes #675
=> Also monitor include-files for changes when --reload is set

CHANGELOG.md, CMakeLists.txt
Some distro's build infrastructure (e.g. gentoo) can use
CMAKE_INSTALL_PREFIX to install to a different location.
When the config path is hardcoded to /etc, CMAKE_INSTALL_PREFIX has no
effect.
Ref: https://bugs.gentoo.org/858797
=> Use CMAKE_INSTALL_SYSCONFDIR instead of /etc

CHANGELOG.md, src/modules/temperature.cpp
implements temperature in Kelvin for the temperature module
implements idea #2774
- just 2 lines for the formatting options of internal/temperature, I can do that, if you want
=> Kelvin option for module internal/temperature and more accurate calculation of the temperature in °F

CHANGELOG.md, cmake/02-opts.cmake, include/modules/temperature.hpp, include/settings.hpp.cmake, src/modules/temperature.cpp, src/settings.cpp.cmake
CPU's `thermal-zone` changes on every boot on my machine, sometimes it's `1` and other times it's `2`. Others also have had this issue and resorted to scripts updating the `thermal-zone` before starting `polybar`.
This can simply be fixed using a `zone-type` config option:
If you look at the content in `/sys/class/thermal/thermal_zone%zone%/type`, you'll get the name of the sensor and you can easily deduct zone from that. For example for Intel CPUs, you should set `zone-type = x86_pkg_temp` and you'll be set.
Ref #2572
=> feat(temperature): Add `zone-type` setting

CHANGELOG.md, include/drawtypes/label.hpp, src/drawtypes/label.cpp
Closes #2789 
Mention how to do left alignment (right-padding) in the "Token" section of the "Formatting" wiki page
=> negative minimum length adds right padding

CHANGELOG.md, include/cairo/context.hpp
If any rendered text uses a non-integer number of pixels (often emojis),
rendering of subsequent text blocks will start between pixels which
results in small gaps in the background and over/underline colors caused
by cairo only rendering at fractional-intensity in the beginning and end
pixel.
Simply rounding up text width can solve this.
Fixes #2785
=> fix(renderer): Small gaps when rendering emojis

CHANGELOG.md, include/x11/background_manager.hpp, src/components/bar.cpp, src/x11/background_manager.cpp, src/x11/tray_manager.cpp
The background_manager used the root window depth for creating its
pixmaps, but when the root pixmap has a different depth, this causes the
copy_area_checked call to fail and crash the bar.
We now load the root pixmap before finding the visual and creating the
slice pixmaps.
Fixes #2798
=> fix: Crash on root pixmap and window depth mismatch

include/components/eventloop.hpp, src/components/controller.cpp, src/components/eventloop.cpp
Polling the XCB file descriptor for X events doesn't detect events that
are already in XCB's event queue but not yet handled.
If this happens, the eventloop polls for IO and the queued events wait
until another event arrives, causing some desyncs in the bar.
This can easily happen if something (e.g. a click event) triggers some
xcb calls, which as a consequence buffer some incoming events.
We "fix" this by adding a libuv prepare handle (which runs right before
polling for IO) that processes pending X events.
This caused some issues in #2609
=> fix: Handle X events before polling for IO

CHANGELOG.md, include/modules/xwindow.hpp, include/x11/atoms.hpp, include/x11/icccm.hpp, src/modules/xwindow.cpp, src/x11/atoms.cpp, src/x11/icccm.cpp
The xwindow module can now show the contents of the `WM_CLASS` property of the active window. `%instance%` shows the first value and `%class%` shows the second.
Some examples of what applications actually show:
| Application | `%instance%` | `%class%` |
|-|-|-|
|Firefox|Navigator|firefox|
|Thunderbird|Mail|thunderbird|
|Steam|Steam|Steam|
|Spotify|spotify|Spotify|
|rxvt-unicode|urxvt|URxvt|
|xterm|xterm|XTerm|
|Alacritty|Alacritty|Alacritty|
|Vlc|vlc|vlc|
ICCCM Spec: https://x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html#wm_class_property
The new tokens need to be added to the xwindow page. Also describe what they actually do.
=> feat(xwindow): %instance%, %class% from WM_CLASS

CHANGELOG.md, src/modules/backlight.cpp
The issue has been fixed in the linux kernel version 5.9 and above so we are removing our workaround for this from polybar. Users with older versions can still work around this by explicitly setting `use-actual-brightness` to false, it is just not done by default anymore.
Closes #2835
Ref https://bugzilla.kernel.org/show_bug.cgi?id=203905
Ref https://github.com/torvalds/linux/commit/69d9f4278d0f9d24607645f10e5ac5c59c77a4ac
Remove note for default value of `use-actual-brightness`
=> backlight: Remove actual_brightness amdgpu check

CHANGELOG.md, include/modules/ipc.hpp, src/modules/ipc.cpp
Users can now assign separate formats for different hooks inside the IPC module.
Closes #2775 
Changes to documentation
-----
In wiki > Modules > ipc
Examples,
```
[module/demo]
type = custom/ipc
hook-0 = echo foobar
hook-1 = date +%s
hook-2 = whoami
format= <label>
format-0-foreground= ${color.foreground}
format-1-foreground= ${color.foreground}
format-2-foreground= ${color.foreground}
; Based on colors defined by user
format-0-background= ${color.shade1}
format-1-background= ${color.shade2}
format-2-background= ${color.shade3}
initial = 1
click-left = "#demo.hook.0"
click-right = "#demo.hook.1"
double-click-left = "#demo.hook.2"
```
=> Added format-x support for ipc_module, tested with demo config

.clang-tidy, .gitignore, cmake/cxx.cmake, include/components/bar.hpp, include/components/controller.hpp, include/components/eventloop.hpp, include/errors.hpp, include/ipc/ipc.hpp, include/modules/meta/inotify_module.hpp, include/utils/inotify.hpp, include/utils/mixins.hpp, include/x11/connection.hpp, src/components/bar.cpp, src/components/controller.cpp, src/components/eventloop.cpp, src/ipc/ipc.cpp, src/polybar-msg.cpp, src/utils/inotify.cpp
Having the loop return references is nice but you run the risk of having dangling references.
The caller now owns the handle and can choose to extend its lifetime.
This has the advantage of the pointer being valid, even after the handle is closed.
To avoid memory leaks, after closing the handle, we reset all callbacks to free their captures.
=> Make the event loop return shared_ptrs

CHANGELOG.md, include/modules/ipc.hpp, src/modules/ipc.cpp
<label> support for IPC module, 
label=%output%
label-fail=%output%
are now supported in the IPC module
=> <label> support for IPC module

include/ipc/ipc.hpp, src/ipc/ipc.cpp, src/polybar-msg.cpp
In polybar-msg, the connection handle was captured as a reference to a shared_ptr, but the shared_ptr went out of scope right after.
This probably always caused UB, but was only noticeable for two or more instances.
=> fix(ipc): Crash when sending to multiple instances

include/modules/meta/base.inl, src/ipc/encoder.cpp
I tired building polybar with `CMAKE_UNITY_BUILD":"ON"` and the build failed.
The `#pragma once` in base.inl is needed because it is included multiple times when passed to the compiler.
I am not exactly sure why the changes in encoder.cpp are needed. However, both gcc and clang fail. The variable `header` could be renamed Instead of adding `polybar::` to `ipc::header`. However, this would change more lines.
Both changes should have no impact on the runtime ore a normal build.
=> fix code in order to support cmake unity builds

CHANGELOG.md, src/modules/script.cpp
The script module shows a completely empty module if the script didn't produce any output. This is intended behavior, but it doesn't make too much sense if the script also exited with a non-zero exit code.
Ref #2857
The script module docs should explicitly state that an empty output and a zero exit code will hide the script module.
=> script: Require zero exit code to show empty module.

CHANGELOG.md, src/adapters/script_runner.cpp
The module has a poll timeout because it needs to periodically check if it is shutting down. Otherwise, it would be stuck polling and the bar couldn't shut down until the script produces a new line.
However, this causes the bar to wake up intermittently (currently ~40/s) due to the 25ms timeout.
Bumping this to 250ms still gives us timely shut downs and caps the number of wake ups to 4/s.
This is only a stop-gap solution, ideally the script runner is integrated into the main event loop and uses its polling handles which don't have to wake up to check for a shutdown.
Ref #1778
Ref #2337
=> script: Bump poll timeout to 250ms

include/x11/tray_manager.hpp, src/x11/tray_manager.cpp
Reworks settings in the tray module:
* `tray-spacing` (px or pt, default: 0): Space added between tray icons (but not at the beginning or end)
* `tray-padding` (px or pt, default: 0): Space added before and after each tray icon
* `tray-size` (percentage with offset, relative to bar height, default: 66%): Width and height of tray icons, capped at bar height
* `tray-background` (default: bar bg): Background of tray icons. Should really not be altered, only affects the icon itself and not any of the space around it.
* `tray-foreground` (default: bar fg): Hint to the tray applications. Sets the non-standard `_NET_SYSTEM_TRAY_COLORS`
Any other tray settings that used to work in the bar section, do not work in the tray module.
Since the tray module is not yet released, we can do that without it …
=> tray: Rework module settings

doc/conf.py
There is no way to support extlinks with a custom caption in both sphinx < 4 and >= 4 at the same time without implementing different behavior per version.
The usage of `%s` in extlinks caption strings does not work the same in sphinx < 4 and >= 4. Before sphinx 4, %s wasn't allowed and after it is required.
This failed builds on sphinx >= 4
=> fix(doc): %s in extlinks caption before sphinx 4.0

.github/workflows/ci.yml, CHANGELOG.md, include/utils/bspwm.hpp, include/utils/i3.hpp, include/utils/restack.hpp, include/x11/ewmh.hpp, src/CMakeLists.txt, src/components/bar.cpp, src/utils/bspwm.cpp, src/utils/i3.cpp, src/utils/restack.cpp, src/x11/ewmh.cpp
Refactors the restacking algorithms and adds new ones.
The restacking algorithms now only have to provide the sibling window and stacking mode.
**New strategies**
* `ewmh`: Tries to put the bar window above the _NET_SUPPORTING_WM_CHECK window
* `bottom`: Puts the bar window at the bottom of the window stack (same as the old generic strategy)
The generic strategy is now a best effort strategy which simply tries out other strategy until it finds a suitable one. Currently it first tries ewmh, then bottom.
Additionally, the `bspwm` strategy also first tries ewmh before falling back to searching for the dedicated root windows for each monitor.
Fixes #2873
May also work for #2543
Add the new strategies as well as the changes to the strategy to the wiki.
Also mention that generic is best-effort, …
=> Restack refactoring

src/x11/extensions/randr.cpp
When using `get_screen_resources`, XRandR will query the hardware to
detect any change. This takes some time.
`get_screen_resources_current` uses the cached information and is
pretty fast.
In my case, the information is always already present in cache because
it was set by the program that did configure the screens (autorandr in
my case, but this applies to most frontends). As polybar is not used
to configure stuff, I think this is fine. There should be something
configuring the screen before polybar is able to use it.
However, maybe some people are using `polybar --list-monitors` just
after plugging a screen. It won't display the new screen in this case.
So, maybe this is not a good idea. It makes polybar starts
faster (500ms faster in my case when there are 3 screens plugged).
Also, I …
=> fix(randr): avoid querying hardware to get current configuration

src/x11/tray_manager.cpp
Fixes an issue where the tray docking logic does not account for the tray's visibility when docking new clients. 
The fix is relatively simple as it just sets `client->hidden` to the tray's manager's before calling `ensure_state`. 
Fixes #2968
=> fix(tray): check for visibility when docking

CHANGELOG.md, include/utils/bspwm.hpp, src/components/bar.cpp, src/utils/bspwm.cpp
The ewmh strategy has to be dropped because the
`_NET_SUPPORTING_WM_CHECK` window may (at least in bspwm) appear anywhere in the window stack.
To fix the overlapping monitors issue in #2873, we simply restack against the topmost of these root windows.
Fixes #2972
Fixes #2873 (again)
The `bspwm` strategy documentation has to be revised slightly.
=> fix(bspwm): Restack against topmost root window.

CHANGELOG.md, include/modules/backlight.hpp, src/modules/backlight.cpp
The `backlight` file seems to not receive modification events for inotify (it does receive other events though).
These other events still trigger an update, but the value read is still the old value because the events arrive just slightly before the file is updated.
The new `poll-interval` setting will inject an event every X seconds to force an update.
If the actual_brightness file is used, the interval is set to 0 and thus turned off.
This does not add any more wakeups to the module, the inotify modules wake up every second anyway and during that time, the interval is checked.
Fixes #2835
Document `poll-interval` and maybe better describe the recommended settings.
=> fix(backlight): Poll if necessary

doc/requirements.txt
The notfound plugin (404 page) does not seem to work with older versions of the theme.
=> doc: Bump sphinx-rtd-theme to version 2

CHANGELOG.md, include/modules/xworkspaces.hpp, src/modules/xworkspaces.cpp
We had someone else get bit by this, so I figured why not pick up the (pretty much already done) patch by @scaramangado from #2603 and add some docs.
By default, we group workspaces by monitor with the help of _NET_DESKTOP_VIEWPORT.  However, some users may experience this as an unpredictable "shuffling" of workspaces.  While WMs could disable advertising the property itself, it seems more sensible to handle this at the level of polybar.  Hence, introduce a new group-by-monitor flag—defaulting to true—which can be used to disable this behaviour.
Closes: https://github.com/polybar/polybar/issues/2603
Related: https://github.com/xmonad/xmonad-contrib/pull/791
Related: https://github.com/qtile/qtile/issues/3375
I suppose documentation of the flag, as well as the incompatibility with …
=> feat(xworkspaces): Add group-by-monitor flag

.github/workflows/release.yml, CHANGELOG.md, doc/dev/release-workflow.rst, doc/migration/3.7/index.rst, version.txt
See `CHANGELOG.md` for full changelog.
Currently, this release is scheduled for *Sunday November 5th*.
The GitHub release draft is [here](https://github.com/polybar/polybar/releases/edit/untagged-f31abffc40b374a3e92e) (members only)
* https://github.com/polybar/polybar.github.io/pull/48
The wiki is updated with all changes (as described in all the PRs for this release):
- https://github.com/polybar/polybar/pull/2630
- https://github.com/polybar/polybar/pull/2664
- https://github.com/polybar/polybar/pull/2676
- https://github.com/polybar/polybar/pull/2595
- https://github.com/polybar/polybar/pull/2700
- https://github.com/polybar/polybar/pull/2705
- https://github.com/polybar/polybar/pull/2728
- https://github.com/polybar/polybar/pull/2784
- https://github.com/polybar/polybar/pull/2752
- …
=> Version 3.7.0

CHANGELOG.md, include/events/signal.hpp, include/events/signal_fwd.hpp, include/modules/meta/base.hpp, include/modules/tray.hpp, include/x11/legacy_tray_manager.hpp, include/x11/tray_manager.hpp, src/components/renderer.cpp, src/modules/tray.cpp, src/x11/legacy_tray_manager.cpp, src/x11/tray_manager.cpp
Modules that don't produce any output are hidden by the controller (don't have margins or separators).
The tray module should also do that for `format = <tray>` when there are no icons.
This required the visibility handling to be tied to the module visibility instead of being handled by the renderer. Otherwise, the renderer would hide the tray (because the %{Pt} tag was never sent) and the tray would not unhide when new icons appeared; it can't differentiate between hidden because empty and hidden because the module is hidden by the user (the latter is the reason the renderer does hiding at all).
Fixes #3036
=> fix(tray): Allow module to disappear for empty tray

doc/requirements.txt
Ref: https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj
Will also be backported to 3.7.2
=> fix(doc): Update vulnerable rtd search extension

CHANGELOG.md, doc/user/actions.rst, include/modules/alsa.hpp, include/modules/pulseaudio.hpp, src/modules/alsa.cpp, src/modules/pulseaudio.cpp
Added the option `unmute-on-scroll` to the `alsa` and `pulseaudio` modules. If this option is false (The default) then there is no difference in behaviour from the previous version. If the option is true, when the user uses the scrollwheel on the module, the sound will be unmuted.
Closes #3067
It might be worth to mention this as an option in the wiki, so that folks could be aware of it.
=> Audio unmute on scroll

CHANGELOG.md, include/modules/backlight.hpp
Applies #3080 to the 3.7.2 hotfix branch. Thanks to @unclechu for fixing this!
Closes #3080
=> Fix backlight initial value matching the actual brightness level

CHANGELOG.md, src/drawtypes/label.cpp
This is just #3087 ported to the 3.7.2 release branch
Closes #3087 
Fixes #3074
=> fix(label): Misbehaving min-length tokens with non-ASCII characters

.clang-tidy, CHANGELOG.md, src/components/renderer.cpp
Without override-redirect, i3 will not allow you to have a non-full-width bar. But polybar simply ignores that request and continues to render the user-requested width instead of the width i3 has configured the window to be.
With the 3.7 release, we started setting the window's backing pixmap to the rendering pixmap. In the case above, the pixmap would only be allocted for the smaller width and when i3 maps the window, it repeats the backing pixmap to fill the entire window.
At the point where i3 maps the window, the pixmap contains an initial render of the bar without module content and that render is then duplicated.
Reverting back to the old approach of simply copying over the pixmap after each render does not have that problem and the remainder of the bar is black (or fully …
=> fix(i3): Properly render non-full-width windows

CHANGELOG.md, include/modules/meta/base.inl, include/utils/command.hpp, src/adapters/script_runner.cpp, src/utils/command.cpp
When a script with `tail = true` received multiple lines quickly, the ones after the first would get buffered and never displayed.
Also, if the cache started rebuilding right after the first line and the second line was received while doing so, then the second line would't get displayed.
Fixes #3117
=> fix(script): Receiving multiple lines rapidly only displays first line

.github/workflows/ci.yml, .github/workflows/release.yml
`checkout` is bumped from v3 to v4, there shouldn't be any breaking changes (just bumps the node version)
`upload-artifact` is bumped from v2 to v4, our use case shouldn't break
`github-script` is bumped from v3 to v7. I don't see any breaking changes that should affect us. Again mainly a nodejs version bump
Also adds the codecov token to the coverage action. This is required for uploads on the `master` branch.
=> ci: Update github actions

src/modules/battery.cpp
On the Lenovo X13s, the battery firmware returns a negative value for `power_now`, which is interpreted by the battery module as `0UL` because it converts the `string` to `unsigned long`. This should be read as a `long` instead, as the kernel specifies that `power_now` is an `int`: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/power_supply.h?h=v6.0.11#n99
=> fix(modules/battery): make rate positive if negative

.clang-tidy, CHANGELOG.md, src/x11/background_manager.cpp
If the root pixmap does not fully cover the bar window, some pseudo-transparent areas were filled with unitialized data, causing pixelation or other rendering artifacts.
Now, observed background slices are first filled with black to make sure this does not happen and they print an error if not the full pixmap can be filled.
Fixes #3041
=> fix(render): Deal with incomplete wallpapers

.github/workflows/release.yml
github.* doesn't exist anymore. Instead everything there is now available under github.rest.*
Ref: https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.0.0
=> fix(ci): Release workflow

include/ipc/decoder.hpp, include/ipc/encoder.hpp, include/ipc/msg.hpp, include/utils/color.hpp, include/utils/string.hpp, src/ipc/encoder.cpp, src/utils/color.cpp
In GCC 15, cstdint is less commonly included in stdlib headers so we need explicit includes: https://gcc.gnu.org/gcc-15/porting_to.html
See-Also: https://bugs.gentoo.org/937526
No user facing changes, just build time fixes for GCC 15.
https://bugs.gentoo.org/937526
https://gcc.gnu.org/gcc-15/porting_to.html
=> add missing cstdint includes

CMakeLists.txt
Checks if command `git rev-parse --show-toplevel` matches CMake variable `PROJECT_SOURCE_DIR` if it does, then it checks for the git tags for version information as it was doing before.
If directories do not match, it falls back to version.txt
**Considerations**:
- Code assumes that if `git rev-parse ...` does not return 0, `git describe ...` won't either.
- Message shown on mismatch (`CMake and git directory mismatch, falling back to built-in version information.`) could be clearer and also include that `git` may not be installed
- > This still may get "wrong" results if someone is just putting the polybar sources at the top of some other repo. But that case is not distinguishable from polybar forks anyway and is acceptable
Fixes #3152
=> fix: check if git top-level directory matches CMake project source

CHANGELOG.md, CMakeLists.txt
Backports #3156 (which fixes #3152) to 3.7.3
=> fix: check if git top-level directory matches CMake project source (#3152)

CHANGELOG.md, include/components/screen.hpp, src/components/screen.cpp
On laptops and similar devices, RandR sometimes returns zero active screens, for example when closing a laptop's lid before it suspends.
Don't restart in that case because the new polybar instance will see zero screens and quit. Instead, just ignore those kind of events.
Fixes #2418.
=> fix: don't restart if zero active screens are reported

CHANGELOG.md, src/adapters/pulseaudio.cpp
Instead of preserving the proportions of PulseAudio channels, we now preserve the balance between the channels. This mirrors pulsemixer's approach.
Fixes #3123
=> fix(pulseaudio): Preserve channel balance

CHANGELOG.md, include/x11/tray_manager.hpp, src/x11/tray_manager.cpp
New config option 'tray-reversed' for tray module that makes icons appear in reversed order.
Closes #3183 
Update tray module wiki page
=> Implement tray-reversed option
